/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2023 Clourneysemi Corporation. */

#ifndef _SWITCH_MAC_RANGE_H_
#define _SWITCH_MAC_RANGE_H_

enum {
	RESERVED_DMAC_ADDR_RANGE_ARG_STARTADDR,
	RESERVED_DMAC_ADDR_RANGE_ARG_STOPADDR,
	RESERVED_DMAC_ADDR_RANGE_ARG_DROPENABLE,
	RESERVED_DMAC_ADDR_RANGE_ARG_SENDTOCPU,
	RESERVED_DMAC_ADDR_RANGE_ARG_FORCEQUEUE,
	RESERVED_DMAC_ADDR_RANGE_ARG_EQUEUE,
	RESERVED_DMAC_ADDR_RANGE_ARG_COLOR,
	RESERVED_DMAC_ADDR_RANGE_ARG_FORCECOLOR,
	RESERVED_DMAC_ADDR_RANGE_ARG_MMPVALID,
	RESERVED_DMAC_ADDR_RANGE_ARG_MMPPTR,
	RESERVED_DMAC_ADDR_RANGE_ARG_MMPORDER,
	RESERVED_DMAC_ADDR_RANGE_ARG_ENABLE,
};

enum {
	RESERVED_SMAC_ADDR_RANGE_ARG_STARTADDR,
	RESERVED_SMAC_ADDR_RANGE_ARG_STOPADDR,
	RESERVED_SMAC_ADDR_RANGE_ARG_DROPENABLE,
	RESERVED_SMAC_ADDR_RANGE_ARG_SENDTOCPU,
	RESERVED_SMAC_ADDR_RANGE_ARG_FORCEQUEUE,
	RESERVED_SMAC_ADDR_RANGE_ARG_EQUEUE,
	RESERVED_SMAC_ADDR_RANGE_ARG_COLOR,
	RESERVED_SMAC_ADDR_RANGE_ARG_FORCECOLOR,
	RESERVED_SMAC_ADDR_RANGE_ARG_MMPVALID,
	RESERVED_SMAC_ADDR_RANGE_ARG_MMPPTR,
	RESERVED_SMAC_ADDR_RANGE_ARG_MMPORDER,
	RESERVED_SMAC_ADDR_RANGE_ARG_ENABLE,
};

enum {
	L2_RESERVED_MULTI_ADDR_ARG_MACBASE,
	L2_RESERVED_MULTI_ADDR_ARG_MASK,
};

enum {
	L2_RESERVED_MULTI_ADDR_ARG_DROPMASK,
	L2_RESERVED_MULTI_ADDR_ARG_SENDTOCPUMASK,
};

int switch_mac_range_config(int argc, char **argv);
void switch_mac_range_usage(void);

#endif /* _SWITCH_MAC_RANGE_H_ */
