/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2023 Clourneysemi Corporation. */

#ifndef _SWITCH_TUNNEL_H_
#define _SWITCH_TUNNEL_H_

enum {
	L2_TUNNEL_DECODER_ARG_DEFAULTETHCTYPEVALID,
	L2_TUNNEL_DECODER_ARG_DEFAULTETHCTYPE,
	L2_TUNNEL_DECODER_ARG_DEFAULTETHSTYPEVALID,
	L2_TUNNEL_DECODER_ARG_DEFAULTETHSTYPE,
};


enum {
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_VALID,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_SNAPLLC_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_SNAPLLC,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_ETHTYPE_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_ETHTYPE,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L3TYPE_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L3TYPE,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_IPSA_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_IPSA,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_IPDA_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_IPDA,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L4TYPE_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L4TYPE,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L4PROTOCOL_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L4PROTOCOL,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L4SP_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L4SP,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L4DP_MASK,
	TUNNEL_EXIT_LOOKUP_TCAM_ARG_L4DP,
};

enum {
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_SRCPORTMASK,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_SENDTOCPU,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_SECONDSHIFT,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_SECONDINCLUDEVLAN,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_DIRECT,
	/*over 64 bits*/
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_KEY,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_KEY0 = TUNNEL_EXIT_LOOKUP_ANSWER_ARG_KEY,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_KEY1,
	/*over 64 bits*/
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_LOOKUPMASK,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_LOOKUPMASK0 = TUNNEL_EXIT_LOOKUP_ANSWER_ARG_LOOKUPMASK,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_LOOKUPMASK1,
	TUNNEL_EXIT_LOOKUP_ANSWER_ARG_TABINDEX,
};

enum {
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_VALID,
	/*over 64 bits*/
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_PKTKEY_MASK,
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_PKTKEY_MASK0 = SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_PKTKEY_MASK,
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_PKTKEY_MASK1,
	/*over 64 bits*/
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_PKTKEY,
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_PKTKEY0 = SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_PKTKEY,
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_PKTKEY1,
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_TABKEY_MASK,
	SECOND_TUNNEL_EXIT_LOOKUP_TCAM_ARG_TABKEY,
};

enum {
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_HOWMANYBYTESTOREMOVE,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_UPDATEETHTYPE,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_ETHTYPE,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_REMOVEVLAN,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_UPDATEL4PROTOCOL,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_L4PROTOCOL,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_WHERETOREMOVE,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_DROPPKT,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_DONTEXIT,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_REPLACEVID,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_NEWVID,
	SECOND_TUNNEL_EXIT_LOOKUP_ANSWER_ARG_TUNNELEXITEGRESSPTR,
};

enum {
	EGRESS_TUNNEL_EXIT_ARG_HOWMANYBYTESTOREMOVE,
	EGRESS_TUNNEL_EXIT_ARG_UPDATEETHTYPE,
	EGRESS_TUNNEL_EXIT_ARG_ETHTYPE,
	EGRESS_TUNNEL_EXIT_ARG_REMOVEVLAN,
	EGRESS_TUNNEL_EXIT_ARG_UPDATEL4PROTOCOL,
	EGRESS_TUNNEL_EXIT_ARG_L4PROTOCOL,
	EGRESS_TUNNEL_EXIT_ARG_WHERETOREMOVE,
};

enum {
	/*over 64 bits*/
	TUNNEL_ENTRY_HEADER_ARG_DATA,
	TUNNEL_ENTRY_HEADER_ARG_DATA0 = TUNNEL_ENTRY_HEADER_ARG_DATA,
	TUNNEL_ENTRY_HEADER_ARG_DATA1,
	TUNNEL_ENTRY_HEADER_ARG_DATA2,
	TUNNEL_ENTRY_HEADER_ARG_DATA3,
	TUNNEL_ENTRY_HEADER_ARG_DATA4,
	TUNNEL_ENTRY_HEADER_ARG_DATA5,
	TUNNEL_ENTRY_HEADER_ARG_DATA6,
	TUNNEL_ENTRY_HEADER_ARG_DATA7,
	TUNNEL_ENTRY_HEADER_ARG_DATA8,
	TUNNEL_ENTRY_HEADER_ARG_DATA9,
};

enum {
	L2_TUNNEL_ENTRY_INSTR_ARG_L3TYPE,
	L2_TUNNEL_ENTRY_INSTR_ARG_HASUDP,
	L2_TUNNEL_ENTRY_INSTR_ARG_UPDATEETHERTYPE,
	L2_TUNNEL_ENTRY_INSTR_ARG_OUTERETHERTYPE,
};

enum {
	TUNNEL_ENTRY_INSTR_ARG_TUNNELENTRYTYPE,
	TUNNEL_ENTRY_INSTR_ARG_INSERTLENGTH,
	TUNNEL_ENTRY_INSTR_ARG_LENGTHPOS,
	TUNNEL_ENTRY_INSTR_ARG_LENGTHNEGOFFSET,
	TUNNEL_ENTRY_INSTR_ARG_LENGTHPOSOFFSET,
	TUNNEL_ENTRY_INSTR_ARG_INCVLANSINLENGTH,
	TUNNEL_ENTRY_INSTR_ARG_TUNNELHEADERPTR,
	TUNNEL_ENTRY_INSTR_ARG_TUNNELHEADERLEN,
};

int switch_tunnel_config(int argc, char **argv);
void switch_tunnel_usage(void);

#endif /* _SWITCH_TUNNEL_H_ */
