/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2023 Clourneysemi Corporation. */

#ifndef _SWITCH_VLAN_H_
#define _SWITCH_VLAN_H_

enum {
	VLAN_TABLE_ARG_VLANPORTMASK,
	VLAN_TABLE_ARG_GID,
	VLAN_TABLE_ARG_MMPVALID,
	VLAN_TABLE_ARG_MMPPTR,
	VLAN_TABLE_ARG_MMPORDER,
	VLAN_TABLE_ARG_MSPTPTR,
	VLAN_TABLE_ARG_VLANSINGLEOP,
	VLAN_TABLE_ARG_VIDSEL,
	VLAN_TABLE_ARG_CFIDEISEL,
	VLAN_TABLE_ARG_PCPSEL,
	VLAN_TABLE_ARG_NRVLANSVIDOPERATIONIF,
	VLAN_TABLE_ARG_VLANSINGLEOPIF,
	VLAN_TABLE_ARG_VIDSELIF,
	VLAN_TABLE_ARG_CFIDEISELIF,
	VLAN_TABLE_ARG_PCPSELIF,
	VLAN_TABLE_ARG_TYPESELIF,
	VLAN_TABLE_ARG_VIDIF,
	VLAN_TABLE_ARG_PCPIF,
	VLAN_TABLE_ARG_CFIDEIIF,
	VLAN_TABLE_ARG_TYPESEL,
	VLAN_TABLE_ARG_VID,
	VLAN_TABLE_ARG_PCP,
	VLAN_TABLE_ARG_CFIDEI,
	VLAN_TABLE_ARG_ALLOWROUTING,
	VLAN_TABLE_ARG_SENDIPMCTOCPU,
};

int switch_vlan_config(int argc, char **argv);
void switch_vlan_usage(void);

#endif /* _SWITCH_VLAN_H_ */
