/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2023 Clourneysemi Corporation. */

#ifndef _SWITCH_LEARNING_H_
#define _SWITCH_LEARNING_H_

enum {
	LEARNING_AND_AGING_ARG_LEARNINGENABLE,
	LEARNING_AND_AGING_ARG_AGINGENABLE,
	LEARNING_AND_AGING_ARG_DAHITENABLE,
	LEARNING_AND_AGING_ARG_LRU,
};

enum {
	SOFTWARE_AGING_ENABLE_ARG_ENABLE,
};

enum {
	LEARNING_PACKET_CONTROL_ARG_HWLEARNINGWRITEBACK,
	LEARNING_PACKET_CONTROL_ARG_HWAGINGWRITEBACK,
	LEARNING_PACKET_CONTROL_ARG_HWHITWRITEBACK,
};

enum {
	LEARNING_DATA_FIFO_ARG_MAC,
	LEARNING_DATA_FIFO_ARG_GID,
	LEARNING_DATA_FIFO_ARG_DESTADDRESS,
	LEARNING_DATA_FIFO_ARG_UC,
	LEARNING_DATA_FIFO_ARG_PORT_OR_PTR,
	LEARNING_DATA_FIFO_ARG_DROP,
	LEARNING_DATA_FIFO_ARG_L2ACTIONTABLEDASTATUS,
	LEARNING_DATA_FIFO_ARG_L2ACTIONTABLESASTATUS,
	LEARNING_DATA_FIFO_ARG_METADATA,
	LEARNING_DATA_FIFO_ARG_STATUS,
	LEARNING_DATA_FIFO_ARG_TYPE,
	LEARNING_DATA_FIFO_ARG_VALID,
};

enum {
	LEARNING_CONFLICT_ARG_VALID,
	LEARNING_CONFLICT_ARG_MACADDR,
	LEARNING_CONFLICT_ARG_GID,
	LEARNING_CONFLICT_ARG_PORT,
};

enum {
	LEARNING_OVERFLOW_ARG_VALID,
	LEARNING_OVERFLOW_ARG_MACADDR,
	LEARNING_OVERFLOW_ARG_GID,
	LEARNING_OVERFLOW_ARG_PORT,
};

enum {
	LEARNING_DA_MAC_ARG_MAC,
	LEARNING_DA_MAC_ARG_ENABLE,
};

int switch_learning_config(int argc, char **argv);
void switch_learning_usage(void);

#endif /* _SWITCH_LEARNING_H_ */
