/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2023 Clourneysemi Corporation. */

#ifndef _SWITCH_NAT_H_
#define _SWITCH_NAT_H_

enum {
	NAT_ACTION_TABLE_ARG_ACTION,
};

enum {
	EGRESS_PORT_NAT_STATE_ARG_PORTSTATE,
};

enum {
	INGRESS_NAT_ACTION_ARG_REPLACESRC,
	INGRESS_NAT_ACTION_ARG_REPLACEIP,
	INGRESS_NAT_ACTION_ARG_REPLACEL4PORT,
	INGRESS_NAT_ACTION_ARG_IPADDRESS,
	INGRESS_NAT_ACTION_ARG_PORT,
};

enum {
	EGRESS_NAT_ACTION_ARG_REPLACESRC,
	EGRESS_NAT_ACTION_ARG_REPLACEIP,
	EGRESS_NAT_ACTION_ARG_REPLACEL4PORT,
	EGRESS_NAT_ACTION_ARG_IPADDRESS,
	EGRESS_NAT_ACTION_ARG_PORT,
};

enum {
	NAT_ADD_EGRESS_PORT_FOR_NAT_CAL_ARG_DONTADDINGRESS,
	NAT_ADD_EGRESS_PORT_FOR_NAT_CAL_ARG_DONTADDEGRESS,
};

int switch_nat_config(int argc, char **argv);
void switch_nat_usage(void);

#endif /* _SWITCH_NAT_H_ */
