/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2023 Clourneysemi Corporation. */

#ifndef _SWITCH_L2_H_
#define _SWITCH_L2_H_

#define L2_DA_HASH_LOOKUP_TABLE_BUCKET_MAX              4

enum {
	L2_DESTINATION_TABLE_ARG_UC,
	L2_DESTINATION_TABLE_ARG_DESTPORT_OR_MCADDR,
	L2_DESTINATION_TABLE_ARG_PKTDROP,
	L2_DESTINATION_TABLE_ARG_L2ACTIONTABLEDASTATUS,
	L2_DESTINATION_TABLE_ARG_L2ACTIONTABLESASTATUS,
	L2_DESTINATION_TABLE_ARG_METADATA,
};


//L2 Lookup Collision Table (Masks)
enum {
	L2_LOOKUP_COLLISION_ARG_MACADDR,
	L2_LOOKUP_COLLISION_ARG_GID,
};

enum {
	L2_MULTICAST_TABLE_ARG_MCPORTMASK,
	L2_MULTICAST_TABLE_ARG_METADATA,
};

enum {
	L2_ACTION_TABLE_ARG_NOLEARNINGUC,
	L2_ACTION_TABLE_ARG_NOLEARNINGMC,
	L2_ACTION_TABLE_ARG_DROPALL,
	L2_ACTION_TABLE_ARG_DROP,
	L2_ACTION_TABLE_ARG_DROPPORTMOVE,
	L2_ACTION_TABLE_ARG_SENDTOCPU,
	L2_ACTION_TABLE_ARG_FORCESENDTOCPUORIGPKT,
	L2_ACTION_TABLE_ARG_NOPORTMOVE,
	L2_ACTION_TABLE_ARG_USESPECIALALLOW,
	L2_ACTION_TABLE_ARG_ALLOWPTR,
	L2_ACTION_TABLE_ARG_MMPVALID,
	L2_ACTION_TABLE_ARG_MMPPTR,
	L2_ACTION_TABLE_ARG_MMPORDER,
};

enum {
	L2_ACTION_TABLE_SPORT_ARG_NOLEARNINGUC,
	L2_ACTION_TABLE_SPORT_ARG_NOLEARNINGMC,
	L2_ACTION_TABLE_SPORT_ARG_DROPALL,
	L2_ACTION_TABLE_SPORT_ARG_DROP,
	L2_ACTION_TABLE_SPORT_ARG_DROPPORTMOVE,
	L2_ACTION_TABLE_SPORT_ARG_SENDTOCPU,
	L2_ACTION_TABLE_SPORT_ARG_FORCESENDTOCPUORIGPKT,
	L2_ACTION_TABLE_SPORT_ARG_NOPORTMOVE,
	L2_ACTION_TABLE_SPORT_ARG_USESPECIALALLOW,
	L2_ACTION_TABLE_SPORT_ARG_ALLOWPTR,
	L2_ACTION_TABLE_SPORT_ARG_MMPVALID,
	L2_ACTION_TABLE_SPORT_ARG_MMPPTR,
	L2_ACTION_TABLE_SPORT_ARG_MMPORDER,
};


enum {
       L2_AGING_TABLE_ARG_VALID,
       L2_AGING_TABLE_ARG_STAT,
       L2_AGING_TABLE_ARG_HIT,
};

enum {
       L2_AGING_STATUS_SHADOW_TABLE_ARG_VALID,
};

enum {
	L2_LEARNING_HEADER_ARG_MAC,
	L2_LEARNING_HEADER_ARG_GID,
	L2_LEARNING_HEADER_ARG_UNICAST_PORT_OR_MULTICAST_POINTER,
	L2_LEARNING_HEADER_ARG_UNICAST,
	L2_LEARNING_HEADER_ARG_DROP,
	L2_LEARNING_HEADER_ARG_L2_DESTINATION_TABLE_ADDRESS,
	L2_LEARNING_HEADER_ARG_VALID,
	L2_LEARNING_HEADER_ARG_STATIC,
	L2_LEARNING_HEADER_ARG_HIT,
	L2_LEARNING_HEADER_ARG_L2_ACTION_TABLE_DA_STATUS,
	L2_LEARNING_HEADER_ARG_L2_ACTION_TABLE_SA_STATUS,
	L2_LEARNING_HEADER_ARG_META_DATA,
};

int switch_l2_config(int argc, char **argv);
void switch_l2_usage(void);

#define L2_DEST_TYPE_TABLE		"table"
#define L2_DEST_TYPE_REPLICA		"replica"

#define L2_LOOKUP_ADDR_TYPE_DA		"da"
#define L2_LOOKUP_ADDR_TYPE_SA		"sa"

#define L2_LOOKUP_ACTION_TYPE_ADD	"add"
#define L2_LOOKUP_ACTION_TYPE_DEL	"del"

#define L2_LOOKUP_TYPE_AGING		"aging"
#define L2_LOOKUP_TYPE_SHADOW		"shadow"
#define L2_LOOKUP_TYPE_REPLICA		"replica"

#define L2_COLL_TYPE_TABLE		"table"
#define L2_COLL_TYPE_MASK		"mask"

#define L2_RESERVED_MULTICAST_ADDR_TYPE_DA		"da"
#define L2_RESERVED_MULTICAST_ADDR_TYPE_SA		"sa"

#endif /* _SWITCH_L2_H_ */
