#!/bin/sh /etc/rc.common
#
# Copyright (c) 2021-2025, Clourney Semiconductor. All rights reserved.
#
# This software and/or documentation is licensed by Clourney Semiconductor under limited terms and conditions.
# Reproduction and redistribution in binary or source form, with or without modification,
# for use solely in conjunction with a Clourney Semiconductor chipset, is permitted in condition which
# must retain the above copyright notice.
#
# By using this software and/or documentation, you agree to the limited terms and conditions.

START=98
USE_PROCD=1

VENDOR_HOST_FILE=/etc/vendor_hosts
DNSMASQ_HOST_FILE=/tmp/hosts/dnshijack
NFTABLE_RULE_FILE=/var/run/dnshijack.nft

DNSMASQ_HOST_FILE_TMP=/tmp/dnshijack.hosts
NFTABLE_RULE_FILE_TMP=/tmp/dnshijack.nft

append_dns() {
	append dns "$1" ","
	append hosts "$1"
	dnscnt="$(($dnscnt + 1))"
}

retrieve_dns() {
	dnscnt=0

	while read hostname; do
		append_dns $hostname
	done < $VENDOR_HOST_FILE

	config_load "dns-hijack"
	config_list_foreach "config" "name" append_dns

	if [ $dnscnt -gt 1 ]; then
		dns="{$dns}"
	fi
}

retrieve_mac() {
	mac=$(awk -F '=' '/macwan0/{print $2}' /tmp/sysinfo/board_macaddr)

	if [ -z "$mac" ]; then
		mac=$(ifconfig br-lan | awk '/HWaddr/{print $5}')
	fi

	if [ -z "$mac" ]; then
		logger -t dnshijack "failed to retrieve mac address"
		exit 1
	fi
}

gen_dnsmasq_ipv4_host() {
	ipv4addr=$(ifconfig br-lan | awk '/inet addr/{print substr($2,6)}')

	if [ -z "$ipv4addr" ]; then
		logger -t dnshijack "failed to retrieve ipv4 addr"
		return
	fi

	echo "$ipv4addr $hosts" >> $DNSMASQ_HOST_FILE_TMP
}

gen_dnsmasq_ipv6_host() {
        if [ "$opmode" = "router" ]; then
		ula_prefix="$(uci_get network @globals[0] ula_prefix | cut -d '/' -f 1)"
		if [ -n "$ula_prefix" ]; then
			ipv6addr=$(ifconfig br-lan | awk "/$ula_prefix/"'{print $3}' | sort | head -n 1 | cut -d '/' -f 1)
		fi
	fi

	if [ -z "$ipv6addr" ]; then
		ipv6addr=$(ifconfig br-lan | awk '/Scope:Global/{print $3}' | head -n 1 | cut -d '/' -f 1)
	fi

	if [ -z "$ipv6addr" ]; then
		logger -t dnshijack "failed to retrieve ipv6 addr"
		return
	fi

	echo "$ipv6addr $hosts" >> $DNSMASQ_HOST_FILE_TMP
}

update_dnsmasq_host() {
	gen_dnsmasq_ipv4_host
	gen_dnsmasq_ipv6_host
	if [ ! -s $DNSMASQ_HOST_FILE_TMP ]; then
		logger -t dnshijack "failed to generate dnsmasq host"
		return
	fi

	if cmp -s $DNSMASQ_HOST_FILE_TMP $DNSMASQ_HOST_FILE; then
		rm -f $DNSMASQ_HOST_FILE_TMP
	else
		mv $DNSMASQ_HOST_FILE_TMP $DNSMASQ_HOST_FILE
		service_reload /usr/sbin/dnsmasq
	fi
}

gen_nftable_l2_rule() {
	retrieve_mac
	cat >> "$NFTABLE_RULE_FILE_TMP" <<EOF
table bridge dnshijack {
	chain prerouting {
		type filter hook prerouting priority 0; policy accept;
		meta l4proto udp dns $dns meta pkttype set host ether daddr set $mac
	}
}
EOF
}

gen_nftable_l3_rule() {
	cat >> "$NFTABLE_RULE_FILE_TMP" <<EOF
table inet dnshijack {
	chain prerouting {
		type nat hook prerouting priority 0; policy accept;
		iifname "br-lan" meta l4proto udp dns $dns redirect to :53
	}
}
EOF
}

update_nftable_rule() {
        if [ "$opmode" != "router" ]; then
		gen_nftable_l2_rule
	fi
	gen_nftable_l3_rule

	if ! nft list table inet dnshijack >/dev/null 2>&1; then
		rm -f $NFTABLE_RULE_FILE
	fi

	if cmp -s $NFTABLE_RULE_FILE_TMP $NFTABLE_RULE_FILE; then
		rm -f $NFTABLE_RULE_FILE_TMP
	else
		mv $NFTABLE_RULE_FILE_TMP $NFTABLE_RULE_FILE
		nft delete table bridge dnshijack 2>/dev/null
		nft delete table inet dnshijack 2>/dev/null
		nft -f $NFTABLE_RULE_FILE
	fi
}

start_service() {
	opmode=$(uci_get cls-opmode globals mode)

	retrieve_dns
	if [ $dnscnt -eq 0 ]; then
		logger -t dnshijack "failed to retrieve dns name"
		return
	fi
	update_dnsmasq_host
	update_nftable_rule
}

stop_service() {
	rm -f $NFTABLE_RULE_FILE
	nft delete table bridge dnshijack 2>/dev/null
	nft delete table inet dnshijack 2>/dev/null
	rm -f $DNSMASQ_HOST_FILE
	service_reload /usr/sbin/dnsmasq
}

service_triggers() {
	PROCD_RELOAD_DELAY=2000
	procd_add_reload_trigger "dns-hijack" "cls-opmode"
	procd_add_reload_interface_trigger lan
	procd_add_reload_interface_trigger lan6
}

reload_service() {
	start_service
}
