#
# Copyright 2024 Clourneysemi 
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

CLSGUI_TITLE:=Clsgui Wireless Page 
CLSGUI_DEPENDS:=+clsgui-base

PKG_BUILD_DEPENDS:=
PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.2.3

include ../../clsgui.mk

# call BuildPackage - OpenWrt buildroot signature

