/****************************************************************************
*
* Copyright (c) 2023  Clourney Semiconductor Co.,Ltd.
*
* Permission to use, copy, modify, and/or distribute this software for any
* purpose with or without fee is hereby granted, provided that the above
* copyright notice and this permission notice appear in all copies.
*
* THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
* WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
* MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
* SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
* RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
* NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE
* USE OR PERFORMANCE OF THIS SOFTWARE.
*
*****************************************************************************/

#ifndef CSIGMA_TAGS_H
#define CSIGMA_TAGS_H

enum csigma_cmd_tags {
	CSIGMA_TAG_BASE = 0x1000,
	CSIGMA_AP_GET_INFO_TAG = CSIGMA_TAG_BASE,
	CSIGMA_AP_SET_RADIUS_TAG,
	CSIGMA_AP_SET_WIRELESS_TAG,
	CSIGMA_AP_RESET_DEFAULT_TAG,
	CSIGMA_AP_SET_11N_WIRELESS_TAG,
	CSIGMA_AP_SET_SECURITY_TAG,
	CSIGMA_AP_CA_VERSION_TAG,
	CSIGMA_AP_SET_PMF_TAG,
	CSIGMA_AP_SET_APQOS_TAG,
	CSIGMA_AP_SET_STAQOS_TAG,
	CSIGMA_AP_REBOOT_TAG,
	CSIGMA_AP_CONFIG_COMMIT_TAG,
	CSIGMA_AP_DEAUTH_STA_TAG,
	CSIGMA_AP_GET_MAC_ADDRESS_TAG,
	CSIGMA_AP_GET_PARAMETER_TAG,
	CSIGMA_AP_SET_11D_TAG,
	CSIGMA_AP_SET_11H_TAG,
	CSIGMA_AP_SET_RFEATURE_TAG,
	CSIGMA_AP_SET_HS2_TAG,
	CSIGMA_AP_SEND_ADDBA_REQ_TAG,
	CSIGMA_AP_PRESET_TESTPARAMETERS_TAG,

	/* STA */
	CSIGMA_STA_CA_GET_VERSION_TAG,
	CSIGMA_STA_RESET_DEFAULT_TAG,
	CSIGMA_STA_DEVICE_LIST_INTERFACES_TAG,
	CSIGMA_STA_PRESET_TESTPARAMETERS_TAG,
	CSIGMA_STA_DISCONNECT_TAG,
	CSIGMA_STA_SEND_ADDBA_TAG,
	CSIGMA_STA_GET_MAC_ADDRESS_TAG,
	CSIGMA_STA_GET_INFO_TAG,
	CSIGMA_STA_SET_WIRELESS_TAG,
	CSIGMA_STA_SET_RFEATURE_TAG,
	CSIGMA_STA_SET_IP_CONFIG_TAG,
	CSIGMA_STA_SET_PSK_TAG,
	CSIGMA_STA_ASSOCIATE_TAG,
	CSIGMA_STA_SET_ENCRYPTION_TAG,
	CSIGMA_STA_SET_SECURITY_TAG,
	CSIGMA_DEV_SEND_FRAME_TAG,
	CSIGMA_STA_REASSOC_TAG,
	CSIGMA_STA_SET_SYSTIME_TAG,
	CSIGMA_STA_SET_RADIO_TAG,
	CSIGMA_STA_SET_MACADDR_TAG,
	CSIGMA_STA_SET_UAPSD_TAG,
	CSIGMA_STA_RESET_PARM_TAG,
	CSIGMA_STA_SET_11N_TAG,
	CSIGMA_STA_SET_POWER_SAVE_TAG,
	CSIGMA_STA_SET_SLEEP_TAG,
	CSIGMA_STA_GET_IP_CONFIG_TAG,
	CSIGMA_STA_SCAN_TAG,
	CSIGMA_DEVICE_GET_INFO_TAG,
	CSIGMA_DEV_EXEC_ACTION_TAG,
	CSIGMA_START_WPS_REGISTRATION_TAG,
	CSIGMA_DEV_CONFIGURE_IE_TAG,
	CSIGMA_STA_SET_EAPTLS_TAG,
	CSIGMA_DEV_SET_RFEATURE_TAG,
	CSIGMA_DEV_RESET_DEFAULT_TAG,
	CSIGMA_DEV_GET_PARAMETER_TAG,
	CSIGMA_DEV_SET_CONFIG_TAG,
	CSIGMA_DEV_SEND_1905_TAG,
};

#endif				/* CSIGMA_TAGS_H */
