-- Copyright 2012 Jo-Philipp Wich <jow@openwrt.org>
-- Licensed to the public under the Apache License 2.0.

local m, section, m2, s2
net=string.gsub(luci.sys.exec("uci -q get modem.SIM3.net"),"%s+","")
m = Map("modem", net..translate("Network"))
section = m:section(NamedSection, "SIM3", "rndis", translate("SIM Settings"))
section.anonymous = true
section.addremove = false
	section:tab("general", translate("General Settings"))
	section:tab("advanced", translate("Advanced Settings"))
	section:tab("physical", translate("Physical Settings"))

local function set_status(self)
	-- if current network is empty, print a warning
	--if not net:is_floating() and net:is_empty() then
	--	st.template = "cbi/dvalue"
	--	st.network  = nil
	--	st.value    = translate("There is no device assigned yet, please attach a network device in the \"Physical Settings\" tab")
	--else
		st.template = "admin_network/iface_status"
		st.network  = self
		st.value    = nil
	--end
end

st = section:taboption("general", DummyValue, "__statuswifi", translate("Status"))
st.on_init = set_status("SIM3")

enable = section:taboption("general", Flag, "enable", translate("Enable"))
enable.rmempty  = false

--查询模块型号--
function modem_name(name)
	name=string.gsub(luci.sys.exec("uci -q get system.@system[0].SIM3_name | grep "..name.." | wc -l"),"%s+","")
	return name
end


apn = section:taboption("general", Value, "apn", translate("APN"))

username = section:taboption("general", Value, "username", translate("Username"))

password = section:taboption("general", Value, "password", translate("Password"))
password.password = true

auth_type = section:taboption("general", ListValue, "auth_type", translate("Auth Type"))
auth_type:value("0", translate"none")
auth_type:value("1", "pap")
auth_type:value("2", "chap")
if modem_name("mv31w") == "1" then
	auth_type:value("3", "mschapv2")
elseif modem_name("650") == "1" or modem_name("160") == "1" or modem_name("150-NA") == "1" or modem_name("668") == "1" then
	auth_type:value("3", "pap/chap")
elseif modem_name("500U") == "1" then
	auth_type:value("3", "pap/chap")
elseif modem_name("500Q") == "1" then
	auth_type:value("3", "pap/chap")
elseif modem_name("520N") == "1" then
	auth_type:value("3", "pap/chap")
elseif modem_name("7600") == "1" then
	auth_type:value("3", "pap/chap")
end

if modem_name("5700M-CN") == "1" or modem_name("5711_CN") == "1" then
	plmn = section:taboption("general", Value, "plmn", translate("PLMN"))
end

pincode = section:taboption("general", Value, "pincode", translate("PIN Code"))
---------------------------advanced------------------------------
if modem_name("668") == "1" then
	natmode = section:taboption("advanced", Flag, "natmode", translate("Shared Connection(NAT)"))
end

enable = section:taboption("advanced", Flag, "force_dial", translate("Force Dial"))
enable.rmempty  = false

smode = section:taboption("advanced", ListValue, "smode", translate("Server Type"))
if modem_name("160-JK") == "1" then
smode.default = "6"
smode:value("2", "4G (LTE) Only")
smode:value("4", "5G (NR) Only")
smode:value("6", "4/5G (LTE/NR)")
else
smode.default = "0"
smode:value("0", translate"Automatically")
if modem_name("7600") == "1" then
	smode:value("5", "2G (GSM) Only")
	smode:value("1", "3G (WCDMA) Only")
	smode:value("2", "4G (LTE) Only")
	smode:value("8", "2/3G (GSM/WCDMA)")
	smode:value("9", "2/4G (GSM/LTE)")
	smode:value("3", "3/4G (WCDMA/LTE)")
	smode:value("10", "2/3/4G (GSM/WCDMA/LTE)")
elseif modem_name("668-LA") == "1" then
	smode:value("1", "GSM Only")
	smode:value("2", "UMTS Only")
	smode:value("3", "LTE Only")
	smode:value("4", "GSM And UMTS")
	smode:value("5", "LTE And UMTS")
	smode:value("6", "LTE And GSM")
	smode:value("7", "LTE And UMTS And GSM")
elseif modem_name("668-EU") == "1" then
	smode:value("1", "GSM Only")
	smode:value("2", "UMTS Only")
	smode:value("3", "LTE Only")
	smode:value("4", "GSM And UMTS")
	smode:value("5", "LTE And UMTS")
	smode:value("6", "LTE And GSM")
	smode:value("7", "LTE And UMTS And GSM")
elseif modem_name("668-EAU") == "1" then
	smode:value("1", "GSM Only")
	smode:value("2", "UMTS Only")
	smode:value("3", "LTE Only")
	smode:value("4", "GSM And UMTS")
	smode:value("5", "LTE And UMTS")
	smode:value("6", "LTE And GSM")
	smode:value("7", "LTE And UMTS And GSM")
elseif modem_name("668-JP") == "1" then
	smode:value("2", "UMTS Only")
	smode:value("3", "LTE Only")
	smode:value("5", "LTE And UMTS")
elseif modem_name("668-CN") == "1" then
	smode:value("1", "GSM Only")
	smode:value("2", "UMTS Only")
	smode:value("3", "LTE Only")
	smode:value("4", "GSM And UMTS")
	smode:value("5", "LTE And UMTS")
	smode:value("6", "LTE And GSM")
	smode:value("7", "LTE And UMTS And GSM")
	smode:value("8", "TD-SCDMA")
	smode:value("11", "CDMA")
	smode:value("12", "CDMA And EVDO")
	smode:value("13", "EVDO Only")
elseif modem_name("5711_CN") == "1" or modem_name("5700M-CN") == "1" then
	--smode:value("1", "3G (WCDMA) Only")
	smode:value("2", "4G (LTE) Only")
	smode:value("4", "5G (NR) Only")
	--smode:value("3", "3/4G (WCDMA/LTE)")
	smode:value("6", "4/5G (LTE/NR)")
	--smode:value("7", "3/4/5G(WCDMA/LTE/NR5G)")
else
	smode:value("1", "3G (WCDMA) Only")
	smode:value("2", "4G (LTE) Only")
	smode:value("4", "5G (NR) Only")
	smode:value("3", "3/4G (WCDMA/LTE)")
	smode:value("6", "4/5G (LTE/NR)")
	smode:value("7", "3/4/5G(WCDMA/LTE/NR5G)")
end
end


if modem_name("650") == "1" then
if string.gsub(luci.sys.exec("uci -q get system.@system[0].SIM3_version | awk -F '.' '{print$(NF-1)}'"),"%s+","") == "17" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("101", translate("BAND 1"))
	bandlist_lte:value("103", translate("BAND 3"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("108", translate("BAND 8"))
	bandlist_lte:value("134", translate("BAND 34"))
	bandlist_lte:value("138", translate("BAND 38"))
	bandlist_lte:value("139", translate("BAND 39"))
	bandlist_lte:value("140", translate("BAND 40"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("501", translate("N 1"))
	bandlist_nr:value("505", translate("N 5"))
	bandlist_nr:value("508", translate("N 8"))
	bandlist_nr:value("5028", translate("N 28"))
	bandlist_nr:value("5041", translate("N 41"))
	bandlist_nr:value("5078", translate("N 78"))
	bandlist_nr:value("5079", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
else
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("2", translate("BAND 2"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("101", translate("BAND 1"))
	bandlist_lte:value("102", translate("BAND 2"))
	bandlist_lte:value("103", translate("BAND 3"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("107", translate("BAND 7"))
	bandlist_lte:value("108", translate("BAND 8"))
	bandlist_lte:value("134", translate("BAND 34"))
	bandlist_lte:value("138", translate("BAND 38"))
	bandlist_lte:value("139", translate("BAND 39"))
	bandlist_lte:value("140", translate("BAND 40"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("501", translate("N 1"))
	bandlist_nr:value("5028", translate("N 28"))
	bandlist_nr:value("5041", translate("N 41"))
	bandlist_nr:value("5078", translate("N 78"))
	bandlist_nr:value("5079", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
end
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~16777215]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")

end

if modem_name("150-NA") == "1" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("2", translate("BAND 2"))
	bandlist_wcdma:value("4", translate("BAND 4"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("102", translate("BAND 2"))
	bandlist_lte:value("104", translate("BAND 4"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("107", translate("BAND 7"))
	bandlist_lte:value("112", translate("BAND 12"))
	bandlist_lte:value("113", translate("BAND 13"))
	bandlist_lte:value("114", translate("BAND 14"))
	bandlist_lte:value("117", translate("BAND 17"))
	bandlist_lte:value("125", translate("BAND 25"))
	bandlist_lte:value("126", translate("BAND 26"))
	bandlist_lte:value("129", translate("BAND 29"))
	bandlist_lte:value("130", translate("BAND 30"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:value("142", translate("BAND 42"))
	bandlist_lte:value("143", translate("BAND 43"))
	bandlist_lte:value("146", translate("BAND 46"))
	bandlist_lte:value("148", translate("BAND 48"))
	bandlist_lte:value("166", translate("BAND 66"))
	bandlist_lte:value("171", translate("BAND 71"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("502", translate("N 2"))
	bandlist_nr:value("505", translate("N 5"))
	bandlist_nr:value("507", translate("N 7"))
	bandlist_nr:value("5012", translate("N 12"))
	bandlist_nr:value("5025", translate("N 25"))
	bandlist_nr:value("5041", translate("N 41"))
	bandlist_nr:value("5066", translate("N 66"))
	bandlist_nr:value("5071", translate("N 71"))
	bandlist_nr:value("5077", translate("N 77"))
	bandlist_nr:value("5078", translate("N 78"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz(FDD)"))
	scs:value("1", translate("30kHz(TDD)"))
	scs.default = "1"
	scs:depends("smode","4")
end

if modem_name("150-AE") == "1" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("3", translate("BAND 3"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("6", translate("BAND 6"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:value("9", translate("BAND 9"))
	bandlist_wcdma:value("19", translate("BAND 19"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("101", translate("BAND 1"))
	bandlist_lte:value("102", translate("BAND 2"))
	bandlist_lte:value("103", translate("BAND 3"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("107", translate("BAND 7"))
	bandlist_lte:value("108", translate("BAND 8"))
	bandlist_lte:value("118", translate("BAND 18"))
	bandlist_lte:value("119", translate("BAND 19"))
	bandlist_lte:value("120", translate("BAND 20"))
	bandlist_lte:value("128", translate("BAND 28"))
	bandlist_lte:value("132", translate("BAND 32"))
	bandlist_lte:value("134", translate("BAND 34"))
	bandlist_lte:value("138", translate("BAND 38"))
	bandlist_lte:value("139", translate("BAND 39"))
	bandlist_lte:value("140", translate("BAND 40"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:value("142", translate("BAND 42"))
	bandlist_lte:value("143", translate("BAND 43"))
	bandlist_lte:value("146", translate("BAND 46"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("501", translate("N 1"))
	bandlist_nr:value("503", translate("N 3"))
	bandlist_nr:value("505", translate("N 5"))
	bandlist_nr:value("507", translate("N 7"))
	bandlist_nr:value("508", translate("N 8"))
	bandlist_nr:value("5020", translate("N 20"))
	bandlist_nr:value("5028", translate("N 28"))
	bandlist_nr:value("5038", translate("N 38"))
	bandlist_nr:value("5040", translate("N 40"))
	bandlist_nr:value("5041", translate("N 41"))
	bandlist_nr:value("5077", translate("N 77"))
	bandlist_nr:value("5078", translate("N 78"))
	bandlist_nr:value("5079", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz(FDD)"))
	scs:value("1", translate("30kHz(TDD)"))
	scs.default = "1"
	scs:depends("smode","4")

end

if modem_name("160-CN") == "1" then
if string.gsub(luci.sys.exec("uci -q get system.@system[0].SIM3_version | awk -F '.' '{print$(NF-2)}'"),"%s+","") == "04" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("101", translate("BAND 1"))
	bandlist_lte:value("103", translate("BAND 3"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("108", translate("BAND 8"))
	bandlist_lte:value("134", translate("BAND 34"))
	bandlist_lte:value("138", translate("BAND 38"))
	bandlist_lte:value("139", translate("BAND 39"))
	bandlist_lte:value("140", translate("BAND 40"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("501", translate("N 1"))
	bandlist_nr:value("5028", translate("N 28"))
	bandlist_nr:value("5041", translate("N 41"))
	bandlist_nr:value("5078", translate("N 78"))
	bandlist_nr:value("5079", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz(FDD)"))
	scs:value("1", translate("30kHz(TDD)"))
	scs.default = "1"
	scs:depends("smode","4")
else
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("101", translate("BAND 1"))
	bandlist_lte:value("103", translate("BAND 3"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("108", translate("BAND 8"))
	bandlist_lte:value("134", translate("BAND 34"))
	bandlist_lte:value("138", translate("BAND 38"))
	bandlist_lte:value("139", translate("BAND 39"))
	bandlist_lte:value("140", translate("BAND 40"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("501", translate("N1"))
	bandlist_nr:value("505", translate("N5"))
	bandlist_nr:value("508", translate("N8"))
	bandlist_nr:value("5028", translate("N28"))
	bandlist_nr:value("5041", translate("N41"))
	bandlist_nr:value("5077", translate("N77"))
	bandlist_nr:value("5078", translate("N78"))
	bandlist_nr:value("5079", translate("N79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz(FDD)"))
	scs:value("1", translate("30kHz(TDD)"))
	scs.default = "1"
	scs:depends("smode","4")
end
end

if modem_name("160-EAU") == "1" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("101", translate("BAND 1"))
	bandlist_lte:value("103", translate("BAND 3"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("107", translate("BAND 7"))
	bandlist_lte:value("108", translate("BAND 8"))
	bandlist_lte:value("120", translate("BAND 20"))
	bandlist_lte:value("128", translate("BAND 28"))
	bandlist_lte:value("132", translate("BAND 32"))
	bandlist_lte:value("138", translate("BAND 38"))
	bandlist_lte:value("140", translate("BAND 40"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:value("142", translate("BAND 42"))
	bandlist_lte:value("143", translate("BAND 43"))
	bandlist_lte:value("146", translate("BAND 46"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("501", translate("N 1"))
	bandlist_nr:value("503", translate("N 3"))
	bandlist_nr:value("505", translate("N 5"))
	bandlist_nr:value("507", translate("N 7"))
	bandlist_nr:value("508", translate("N 8"))
	bandlist_nr:value("5020", translate("N 20"))
	bandlist_nr:value("5028", translate("N 28"))
	bandlist_nr:value("5041", translate("N 41"))
	bandlist_nr:value("5075", translate("N 75"))
	bandlist_nr:value("5076", translate("N 76"))
	bandlist_nr:value("5077", translate("N 77"))
	bandlist_nr:value("5078", translate("N 78"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz(FDD)"))
	scs:value("1", translate("30kHz(TDD)"))
	scs.default = "1"
	scs:depends("smode","4")

end

if modem_name("160-JK") == "1" then
	-- bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	-- bandlist_wcdma:value("0", translate("Automatically"))
	-- bandlist_wcdma:value("1", translate("BAND 1"))
	-- bandlist_wcdma:value("5", translate("BAND 5"))
	-- bandlist_wcdma:value("8", translate("BAND 8"))
	-- bandlist_wcdma:depends("smode","1")
	-- bandlist_wcdma:depends("smode","3")
	-- bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("101", translate("BAND 1"))
	bandlist_lte:value("103", translate("BAND 3"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("107", translate("BAND 7"))
	bandlist_lte:value("108", translate("BAND 8"))
	bandlist_lte:value("118", translate("BAND 18"))
	bandlist_lte:value("119", translate("BAND 19"))
	bandlist_lte:value("126", translate("BAND 26"))
	bandlist_lte:value("128", translate("BAND 28"))
	bandlist_lte:value("139", translate("BAND 39"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:value("142", translate("BAND 42"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("501", translate("N 1"))
	bandlist_nr:value("503", translate("N 3"))
	bandlist_nr:value("507", translate("N 7"))
	bandlist_nr:value("508", translate("N 8"))
	bandlist_nr:value("5028", translate("N 28"))
	bandlist_nr:value("5041", translate("N 41"))
	bandlist_nr:value("5077", translate("N 77"))
	bandlist_nr:value("5078", translate("N 78"))
	bandlist_nr:value("5079", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz(FDD)"))
	scs:value("1", translate("30kHz(TDD)"))
	scs.default = "1"
	scs:depends("smode","4")

end

if modem_name("160-NA") == "1" then
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("102", translate("BAND 2"))
	bandlist_lte:value("104", translate("BAND 4"))
	bandlist_lte:value("105", translate("BAND 5"))
	bandlist_lte:value("112", translate("BAND 12"))
	bandlist_lte:value("113", translate("BAND 13"))
	bandlist_lte:value("114", translate("BAND 14"))
	bandlist_lte:value("129", translate("BAND 29"))
	bandlist_lte:value("130", translate("BAND 30"))
	bandlist_lte:value("141", translate("BAND 41"))
	bandlist_lte:value("146", translate("BAND 46"))
	bandlist_lte:value("148", translate("BAND 48"))
	bandlist_lte:value("166", translate("BAND 66"))
	bandlist_lte:value("171", translate("BAND 71"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("502", translate("N2"))
	bandlist_nr:value("505", translate("N5"))
	bandlist_nr:value("5012", translate("N12"))
	bandlist_nr:value("5014", translate("N14"))
	bandlist_nr:value("5025", translate("N25"))
	bandlist_nr:value("5030", translate("N30"))
	bandlist_nr:value("5041", translate("N41"))
	bandlist_nr:value("5048", translate("N48"))
	bandlist_nr:value("5066", translate("N66"))
	bandlist_nr:value("5070", translate("N70"))
	bandlist_nr:value("5071", translate("N71"))
	bandlist_nr:value("5077", translate("N77"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz(FDD)"))
	scs:value("1", translate("30kHz(TDD)"))
	scs.default = "1"
	scs:depends("smode","4")

end

if modem_name("668-CN") == "1" then
	bandlist_gsm = section:taboption("advanced", ListValue, "band_gsm", translate("Lock GSM Band"))
	bandlist_gsm.default = "0"
	bandlist_gsm:value("0", translate"Automatically")
	bandlist_gsm:value("900", translate"900 MHz Band")
	bandlist_gsm:value("1800", translate"1800 MHz Band")
	bandlist_gsm:depends({smode="1"})
	bandlist_gsm:depends({smode="4"})
	bandlist_gsm:depends({smode="6"})
	bandlist_gsm:depends({smode="7"})
	
	bandlist_umts = section:taboption("advanced", ListValue, "band_umts", translate("Lock UMTS Band"))
	bandlist_umts.default = "0"
	bandlist_umts:value("0", translate"Automatically")
	bandlist_umts:value("1", translate"BAND_UMTS_I")
	bandlist_umts:value("8", translate"BAND_UMTS_VIII")
	bandlist_umts:depends({smode="2"})
	bandlist_umts:depends({smode="4"})
	bandlist_umts:depends({smode="5"})
	bandlist_umts:depends({smode="7"})
	
	bandlist_scdma = section:taboption("advanced", ListValue, "band_scdma", translate("Lock TD-SCDMA Band"))
	bandlist_scdma.default = "0"
	bandlist_scdma:value("0", translate"Automatically")
	bandlist_scdma:value("201", translate"BAND_UMTS_TDD_A")
	bandlist_scdma:value("206", translate"BAND_UMTS_TDD_F")
	bandlist_scdma:depends({smode="8"})
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock LTE Band"))
	bandlist_lte.default = "0"
	bandlist_lte:value("0", translate"Automatically")
	bandlist_lte:value("101", translate"BAND 1")
	bandlist_lte:value("103", translate"BAND 3")
	bandlist_lte:value("105", translate"BAND 5")
	bandlist_lte:value("108", translate"BAND 8")
	bandlist_lte:value("134", translate"BAND 34")
	bandlist_lte:value("138", translate"BAND 38")
	bandlist_lte:value("139", translate"BAND 39")
	bandlist_lte:value("140", translate"BAND 40")
	bandlist_lte:value("141", translate"BAND 41")
	bandlist_lte:depends({smode="3"})
	bandlist_lte:depends({smode="5"})
	bandlist_lte:depends({smode="6"})
	bandlist_lte:depends({smode="7"})
	
	bandlist_cdma = section:taboption("advanced", ListValue, "band_cdma", translate("Lock CDMA or EVDO Band"))
	bandlist_cdma.default = "0"
	bandlist_cdma:value("0", translate"Automatically")
	bandlist_cdma:value("300", translate"BAND_BC0")
	bandlist_cdma:depends({smode="11"})
	bandlist_cdma:depends({smode="12"})
	bandlist_cdma:depends({smode="13"})
elseif modem_name("668-LA") == "1" then
	bandlist_gsm = section:taboption("advanced", ListValue, "band_gsm", translate("Lock GSM Band"))
	bandlist_gsm.default = "0"
	bandlist_gsm:value("0", translate"Automatically")
	bandlist_gsm:value("850", translate"850 MHz Band")
	bandlist_gsm:value("900", translate"900 MHz Band")
	bandlist_gsm:value("1800", translate"1800 MHz Band")
	bandlist_gsm:value("1900", translate"1900 MHz Band")
	bandlist_gsm:depends({smode="1"})
	bandlist_gsm:depends({smode="4"})
	bandlist_gsm:depends({smode="6"})
	bandlist_gsm:depends({smode="7"})
	
	bandlist_umts = section:taboption("advanced", ListValue, "band_umts", translate("Lock UMTS Band"))
	bandlist_umts.default = "0"
	bandlist_umts:value("0", translate"Automatically")
	bandlist_umts:value("1", translate"BAND_UMTS_I")
	bandlist_umts:value("2", translate"BAND_UMTS_II")
	bandlist_umts:value("3", translate"BAND_UMTS_III")
	bandlist_umts:value("4", translate"BAND_UMTS_IV")
	bandlist_umts:value("5", translate"BAND_UMTS_V")
	bandlist_umts:value("8", translate"BAND_UMTS_VIII")
	bandlist_umts:depends({smode="2"})
	bandlist_umts:depends({smode="4"})
	bandlist_umts:depends({smode="5"})
	bandlist_umts:depends({smode="7"})
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock LTE Band"))
	bandlist_lte.default = "0"
	bandlist_lte:value("0", translate"Automatically")
	bandlist_lte:value("101", translate"BAND 1")
	bandlist_lte:value("102", translate"BAND 2")
	bandlist_lte:value("103", translate"BAND 3")
	bandlist_lte:value("104", translate"BAND 4")
	bandlist_lte:value("105", translate"BAND 5")
	bandlist_lte:value("107", translate"BAND 7")
	bandlist_lte:value("108", translate"BAND 8")
	bandlist_lte:value("112", translate"BAND 12")
	bandlist_lte:value("117", translate"BAND 17")
	bandlist_lte:value("128", translate"BAND 28")
	bandlist_lte:value("138", translate"BAND 38")
	bandlist_lte:depends({smode="3"})
	bandlist_lte:depends({smode="5"})
	bandlist_lte:depends({smode="6"})
	bandlist_lte:depends({smode="7"})
elseif modem_name("668-EU") == "1" then
	bandlist_gsm = section:taboption("advanced", ListValue, "band_gsm", translate("Lock GSM Band"))
	bandlist_gsm.default = "0"
	bandlist_gsm:value("0", translate"Automatically")
	bandlist_gsm:value("850", translate"850 MHz Band")
	bandlist_gsm:value("900", translate"900 MHz Band")
	bandlist_gsm:value("1800", translate"1800 MHz Band")
	bandlist_gsm:depends({smode="1"})
	bandlist_gsm:depends({smode="4"})
	bandlist_gsm:depends({smode="6"})
	bandlist_gsm:depends({smode="7"})
	
	bandlist_umts = section:taboption("advanced", ListValue, "band_umts", translate("Lock UMTS Band"))
	bandlist_umts.default = "0"
	bandlist_umts:value("0", translate"Automatically")
	bandlist_umts:value("1", translate"BAND_UMTS_I")
	bandlist_umts:value("5", translate"BAND_UMTS_V")
	bandlist_umts:value("8", translate"BAND_UMTS_VIII")
	bandlist_umts:depends({smode="2"})
	bandlist_umts:depends({smode="4"})
	bandlist_umts:depends({smode="5"})
	bandlist_umts:depends({smode="7"})
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock LTE Band"))
	bandlist_lte.default = "0"
	bandlist_lte:value("0", translate"Automatically")
	bandlist_lte:value("101", translate"BAND 1")
	bandlist_lte:value("103", translate"BAND 3")
	bandlist_lte:value("105", translate"BAND 5")
	bandlist_lte:value("107", translate"BAND 7")
	bandlist_lte:value("108", translate"BAND 8")
	bandlist_lte:value("120", translate"BAND 20")
	bandlist_lte:depends({smode="3"})
	bandlist_lte:depends({smode="5"})
	bandlist_lte:depends({smode="6"})
	bandlist_lte:depends({smode="7"})
elseif modem_name("668-EAU") == "1" then
	bandlist_gsm = section:taboption("advanced", ListValue, "band_gsm", translate("Lock GSM Band"))
	bandlist_gsm.default = "0"
	bandlist_gsm:value("0", translate"Automatically")
	bandlist_gsm:value("850", translate"850 MHz Band")
	bandlist_gsm:value("900", translate"900 MHz Band")
	bandlist_gsm:value("1800", translate"1800 MHz Band")
	bandlist_gsm:depends({smode="1"})
	bandlist_gsm:depends({smode="4"})
	bandlist_gsm:depends({smode="6"})
	bandlist_gsm:depends({smode="7"})
	
	bandlist_umts = section:taboption("advanced", ListValue, "band_umts", translate("Lock UMTS Band"))
	bandlist_umts.default = "0"
	bandlist_umts:value("0", translate"Automatically")
	bandlist_umts:value("1", translate"BAND_UMTS_I")
	bandlist_umts:value("3", translate"BAND_UMTS_III")
	bandlist_umts:value("5", translate"BAND_UMTS_V")
	bandlist_umts:value("7", translate"BAND_UMTS_VII")
	bandlist_umts:value("8", translate"BAND_UMTS_VIII")
	bandlist_umts:depends({smode="2"})
	bandlist_umts:depends({smode="4"})
	bandlist_umts:depends({smode="5"})
	bandlist_umts:depends({smode="7"})
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock LTE Band"))
	bandlist_lte.default = "0"
	bandlist_lte:value("0", translate"Automatically")
	bandlist_lte:value("120", translate"BAND 20")
	bandlist_lte:value("128", translate"BAND 28")
	bandlist_lte:value("138", translate"BAND 38")
	bandlist_lte:value("140", translate"BAND 40")
	bandlist_lte:value("141", translate"BAND 41")
	bandlist_lte:depends({smode="3"})
	bandlist_lte:depends({smode="5"})
	bandlist_lte:depends({smode="6"})
	bandlist_lte:depends({smode="7"})
elseif modem_name("668-JP") == "1" then
	bandlist_umts = section:taboption("advanced", ListValue, "band_umts", translate("Lock UMTS Band"))
	bandlist_umts.default = "0"
	bandlist_umts:value("0", translate"Automatically")
	bandlist_umts:value("1", translate"BAND_UMTS_I")
	bandlist_umts:value("5", translate"BAND_UMTS_V")
	bandlist_umts:value("6", translate"BAND_UMTS_VI")
	bandlist_umts:value("8", translate"BAND_UMTS_VIII")
	bandlist_umts:value("19", translate"BAND_UMTS_XIX")
	bandlist_umts:depends({smode="2"})
	bandlist_umts:depends({smode="4"})
	bandlist_umts:depends({smode="5"})
	bandlist_umts:depends({smode="7"})

	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock LTE Band"))
	bandlist_lte.default = "0"
	bandlist_lte:value("0", translate"Automatically")
	bandlist_lte:value("101", translate"BAND 1")
	bandlist_lte:value("103", translate"BAND 3")
	bandlist_lte:value("108", translate"BAND 8")
	bandlist_lte:value("111", translate"BAND 11")
	bandlist_lte:value("118", translate"BAND 18")
	bandlist_lte:value("119", translate"BAND 19")
	bandlist_lte:value("121", translate"BAND 21")
	bandlist_lte:value("126", translate"BAND 26")
	bandlist_lte:value("128", translate"BAND 28")
	bandlist_lte:value("141", translate"BAND 41")
	bandlist_lte:depends({smode="3"})
	bandlist_lte:depends({smode="5"})
	bandlist_lte:depends({smode="6"})
	bandlist_lte:depends({smode="7"})
end

if modem_name("8200") == "1" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("3", translate("BAND 3"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("6", translate("BAND 6"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:value("9", translate("BAND 9"))
	bandlist_wcdma:value("19", translate("BAND 19"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("1", translate("BAND 1"))
	bandlist_lte:value("3", translate("BAND 3"))
	bandlist_lte:value("5", translate("BAND 5"))
	bandlist_lte:value("7", translate("BAND 7"))
	bandlist_lte:value("8", translate("BAND 8"))
	bandlist_lte:value("18", translate("BAND 18"))
	bandlist_lte:value("19", translate("BAND 19"))
	bandlist_lte:value("26", translate("BAND 26"))
	bandlist_lte:value("28", translate("BAND 28"))
	bandlist_lte:value("34", translate("BAND 34"))
	bandlist_lte:value("38", translate("BAND 38"))
	bandlist_lte:value("39", translate("BAND 39"))
	bandlist_lte:value("40", translate("BAND 40"))
	bandlist_lte:value("41", translate("BAND 41"))
	bandlist_lte:value("42", translate("BAND 42"))
	bandlist_lte:value("43", translate("BAND 43"))
	bandlist_lte:value("48", translate("BAND 48"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G(SA) Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("1", translate("N 1"))
	bandlist_nr:value("3", translate("N 3"))
	bandlist_nr:value("5", translate("N 5"))
	bandlist_nr:value("7", translate("N 7"))
	bandlist_nr:value("8", translate("N 8"))
	bandlist_nr:value("28", translate("N 28"))
	bandlist_nr:value("38", translate("N 38"))
	bandlist_nr:value("40", translate("N 40"))
	bandlist_nr:value("41", translate("N 41"))
	bandlist_nr:value("48", translate("N 48"))
	bandlist_nr:value("77", translate("N 77"))
	bandlist_nr:value("78", translate("N 78"))
	bandlist_nr:value("79", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	bandlist_nsa = section:taboption("advanced", ListValue, "band_nsa", translate("Lock 5G(NSA) Band List"))
	bandlist_nsa:value("0", translate("Automatically"))
	bandlist_nsa:value("1", translate("BAND 1"))
	bandlist_nsa:value("3", translate("BAND 3"))
	bandlist_nsa:value("5", translate("BAND 5"))
	bandlist_nsa:value("7", translate("BAND 7"))
	bandlist_nsa:value("8", translate("BAND 8"))
	bandlist_nsa:value("28", translate("BAND 28"))
	bandlist_nsa:value("38", translate("BAND 38"))
	bandlist_nsa:value("40", translate("BAND 40"))
	bandlist_nsa:value("41", translate("BAND 41"))
	bandlist_nsa:value("48", translate("BAND 48"))
	bandlist_nsa:value("77", translate("BAND 77"))
	bandlist_nsa:value("78", translate("BAND 78"))
	bandlist_nsa:value("79", translate("BAND 79"))
	bandlist_nsa:depends("smode","4")
	bandlist_nsa:depends("smode","6")
	bandlist_nsa:depends("smode","7")
end

if modem_name("500U-CN") == "1" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("2", translate("BAND 2"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("1", translate("BAND 1"))
	bandlist_lte:value("2", translate("BAND 2"))
	bandlist_lte:value("3", translate("BAND 3"))
	bandlist_lte:value("5", translate("BAND 5"))
	bandlist_lte:value("7", translate("BAND 7"))
	bandlist_lte:value("8", translate("BAND 8"))
	bandlist_lte:value("20", translate("BAND 20"))
	bandlist_lte:value("28", translate("BAND 28"))
	bandlist_lte:value("34", translate("BAND 34"))
	bandlist_lte:value("38", translate("BAND 38"))
	bandlist_lte:value("39", translate("BAND 39"))
	bandlist_lte:value("40", translate("BAND 40"))
	bandlist_lte:value("41", translate("BAND 41"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("1", translate("N 1"))
	bandlist_nr:value("28", translate("N 28"))
	bandlist_nr:value("41", translate("N 41"))
	bandlist_nr:value("77", translate("N 77"))
	bandlist_nr:value("78", translate("N 78"))
	bandlist_nr:value("79", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
end

if modem_name("500Q-GL") == "1" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("2", translate("BAND 2"))
	bandlist_wcdma:value("3", translate("BAND 3"))
	bandlist_wcdma:value("4", translate("BAND 4"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("6", translate("BAND 6"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:value("19", translate("BAND 19"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("1", translate("BAND 1"))
	bandlist_lte:value("2", translate("BAND 2"))
	bandlist_lte:value("3", translate("BAND 3"))
	bandlist_lte:value("4", translate("BAND 4"))
	bandlist_lte:value("5", translate("BAND 5"))
	bandlist_lte:value("7", translate("BAND 7"))
	bandlist_lte:value("8", translate("BAND 8"))
	bandlist_lte:value("12", translate("BAND 12"))
	bandlist_lte:value("13", translate("BAND 13"))
	bandlist_lte:value("14", translate("BAND 14"))
	bandlist_lte:value("17", translate("BAND 17"))
	bandlist_lte:value("18", translate("BAND 18"))
	bandlist_lte:value("19", translate("BAND 19"))
	bandlist_lte:value("20", translate("BAND 20"))
	bandlist_lte:value("25", translate("BAND 25"))
	bandlist_lte:value("26", translate("BAND 26"))
	bandlist_lte:value("28", translate("BAND 28"))
	bandlist_lte:value("29", translate("BAND 29"))
	bandlist_lte:value("30", translate("BAND 30"))
	bandlist_lte:value("32", translate("BAND 32"))
	bandlist_lte:value("34", translate("BAND 34"))
	bandlist_lte:value("38", translate("BAND 38"))
	bandlist_lte:value("39", translate("BAND 39"))
	bandlist_lte:value("40", translate("BAND 40"))
	bandlist_lte:value("41", translate("BAND 41"))
	bandlist_lte:value("42", translate("BAND 42"))
	bandlist_lte:value("43", translate("BAND 43"))
	bandlist_lte:value("46", translate("BAND 46"))
	bandlist_lte:value("48", translate("BAND 48"))
	bandlist_lte:value("66", translate("BAND 66"))
	bandlist_lte:value("71", translate("BAND 71"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("1", translate("N 1"))
	bandlist_nr:value("2", translate("N 2"))
	bandlist_nr:value("3", translate("N 3"))
	bandlist_nr:value("5", translate("N 5"))
	bandlist_nr:value("7", translate("N 7"))
	bandlist_nr:value("8", translate("N 8"))
	bandlist_nr:value("12", translate("N 12"))
	bandlist_nr:value("20", translate("N 20"))
	bandlist_nr:value("25", translate("N 25"))
	bandlist_nr:value("28", translate("N 28"))
	bandlist_nr:value("38", translate("N 38"))
	bandlist_nr:value("40", translate("N 40"))
	bandlist_nr:value("41", translate("N 41"))
	bandlist_nr:value("48", translate("N 48"))
	bandlist_nr:value("66", translate("N 66"))
	bandlist_nr:value("71", translate("N 71"))
	bandlist_nr:value("77", translate("N 77"))
	bandlist_nr:value("78", translate("N 78"))
	bandlist_nr:value("79", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
end

if modem_name("520N-EU") == "1"  or modem_name("520N-EB") == "1" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("5", translate("BAND 5"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("1", translate("BAND 1"))
	bandlist_lte:value("3", translate("BAND 3"))
	bandlist_lte:value("5", translate("BAND 5"))
	bandlist_lte:value("7", translate("BAND 7"))
	bandlist_lte:value("8", translate("BAND 8"))
	bandlist_lte:value("20", translate("BAND 20"))
	bandlist_lte:value("28", translate("BAND 28"))
	bandlist_lte:value("32", translate("BAND 32"))
	bandlist_lte:value("38", translate("BAND 38"))
	bandlist_lte:value("40", translate("BAND 40"))
	bandlist_lte:value("41", translate("BAND 41"))
	bandlist_lte:value("42", translate("BAND 42"))
	bandlist_lte:value("43", translate("BAND 43"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("1", translate("N 1"))
	bandlist_nr:value("3", translate("N 3"))
	bandlist_nr:value("5", translate("N 5"))
	bandlist_nr:value("7", translate("N 7"))
	bandlist_nr:value("8", translate("N 8"))
	bandlist_nr:value("20", translate("N 20"))
	bandlist_nr:value("28", translate("N 28"))
	bandlist_nr:value("38", translate("N 38"))
	bandlist_nr:value("40", translate("N 40"))
	bandlist_nr:value("41", translate("N 41"))
	bandlist_nr:value("75", translate("N 75"))
	bandlist_nr:value("76", translate("N 76"))
	bandlist_nr:value("77", translate("N 77"))
	bandlist_nr:value("78", translate("N 78"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Cell Frequency"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	--arfcn.placeholder=translate("[range: 0~16777215]")
	
	pci = section:taboption("advanced", Value, "pci", translate("Cell physical ID"))
	pci:depends("smode","2")
	--pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("Cell physical ID"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("NR sub carrier space(SCS)"))
	scs:value("15", translate("15kHz(FDD)"))
	scs:value("30", translate("30kHz(TDD)"))
	scs:value("120", translate("120kHz(TDD)"))
	scs:value("240", translate("240kHz(TDD)"))
	scs.default = "15"
	scs:depends("smode","4")
	--psc.placeholder=translate("[range: 0~1007]")
end

if modem_name("520N-CN") == "1" then
	bandlist_wcdma = section:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	bandlist_wcdma:value("0", translate("Automatically"))
	bandlist_wcdma:value("1", translate("BAND 1"))
	bandlist_wcdma:value("8", translate("BAND 8"))
	bandlist_wcdma:depends("smode","1")
	bandlist_wcdma:depends("smode","3")
	bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("1", translate("BAND 1"))
	bandlist_lte:value("3", translate("BAND 3"))
	bandlist_lte:value("5", translate("BAND 5"))
	bandlist_lte:value("8", translate("BAND 8"))
	bandlist_lte:value("34", translate("BAND 34"))
	bandlist_lte:value("38", translate("BAND 38"))
	bandlist_lte:value("39", translate("BAND 39"))
	bandlist_lte:value("40", translate("BAND 40"))
	bandlist_lte:value("41", translate("BAND 41"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("1", translate("N 1"))
	bandlist_nr:value("3", translate("N 3"))
	bandlist_nr:value("5", translate("N 5"))
	bandlist_nr:value("8", translate("N 8"))
	bandlist_nr:value("28", translate("N 28"))
	bandlist_nr:value("41", translate("N 41"))
	bandlist_nr:value("78", translate("N 78"))
	bandlist_nr:value("79", translate("N 79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Cell Frequency"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	
	pci = section:taboption("advanced", Value, "pci", translate("Cell physical ID"))
	pci:depends("smode","2")
	
	psc = section:taboption("advanced", Value, "psc", translate("Cell physical ID"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("NR sub carrier space(SCS)"))
	scs:value("15", translate("15kHz(FDD)"))
	scs:value("30", translate("30kHz(TDD)"))
	scs:value("120", translate("120kHz(TDD)"))
	scs:value("240", translate("240kHz(TDD)"))
	scs.default = "15"
	scs:depends("smode","4")
end

if modem_name("5700M-CN") == "1" then
	-- bandlist_wcdma = s1:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	-- bandlist_wcdma:value("0", translate("Automatically"))
	-- bandlist_wcdma:value("1", translate("BAND 1"))
	-- bandlist_wcdma:value("8", translate("BAND 8"))
	-- bandlist_wcdma:depends("smode","1")
	-- bandlist_wcdma:depends("smode","3")
	-- bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("1", translate("BAND 1"))
	bandlist_lte:value("3", translate("BAND 3"))
	bandlist_lte:value("5", translate("BAND 5"))
	bandlist_lte:value("8", translate("BAND 8"))
	bandlist_lte:value("34", translate("BAND 34"))
	bandlist_lte:value("38", translate("BAND 38"))
	bandlist_lte:value("39", translate("BAND 39"))
	bandlist_lte:value("40", translate("BAND 40"))
	bandlist_lte:value("41", translate("BAND 41"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("1", translate("N1"))
	bandlist_nr:value("3", translate("N3"))
	bandlist_nr:value("5", translate("N5"))
	bandlist_nr:value("8", translate("N8"))
	bandlist_nr:value("28", translate("N28"))
	bandlist_nr:value("41", translate("N41"))
	bandlist_nr:value("78", translate("N78"))
	bandlist_nr:value("79", translate("N79"))
	bandlist_nr:value("80", translate("N80(SUL)"))
	bandlist_nr:value("81", translate("N81(SUL)"))
	bandlist_nr:value("83", translate("N83(SUL)"))
	bandlist_nr:value("84", translate("N84(SUL)"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz"))
	scs:value("1", translate("30kHz"))
	scs:value("2", translate("60kHz"))
	scs:value("3", translate("120kHz"))
	scs:value("4", translate("240kHz"))
	scs.default = "1"
	scs:depends("smode","4")

end

if modem_name("5711_CN") == "1" then
	-- bandlist_wcdma = s1:taboption("advanced", ListValue, "band_wcdma", translate("Lock 3G Band List"))
	-- bandlist_wcdma:value("0", translate("Automatically"))
	-- bandlist_wcdma:value("1", translate("BAND 1"))
	-- bandlist_wcdma:value("8", translate("BAND 8"))
	-- bandlist_wcdma:depends("smode","1")
	-- bandlist_wcdma:depends("smode","3")
	-- bandlist_wcdma:depends("smode","7")
	
	bandlist_lte = section:taboption("advanced", ListValue, "band_lte", translate("Lock 4G Band List"))
	bandlist_lte:value("0", translate("Automatically"))
	bandlist_lte:value("1", translate("BAND 1"))
	bandlist_lte:value("3", translate("BAND 3"))
	bandlist_lte:value("5", translate("BAND 5"))
	bandlist_lte:value("8", translate("BAND 8"))
	bandlist_lte:value("34", translate("BAND 34"))
	bandlist_lte:value("38", translate("BAND 38"))
	bandlist_lte:value("39", translate("BAND 39"))
	bandlist_lte:value("40", translate("BAND 40"))
	bandlist_lte:value("41", translate("BAND 41"))
	bandlist_lte:value("59", translate("BAND 59"))
	bandlist_lte:value("62", translate("BAND 62"))
	bandlist_lte:depends("smode","2")
	bandlist_lte:depends("smode","3")
	bandlist_lte:depends("smode","6")
	bandlist_lte:depends("smode","7")
	
	bandlist_nr = section:taboption("advanced", ListValue, "band_nr", translate("Lock 5G Band List"))
	bandlist_nr:value("0", translate("Automatically"))
	bandlist_nr:value("1", translate("N1"))
	bandlist_nr:value("3", translate("N3"))
	bandlist_nr:value("5", translate("N5"))
	bandlist_nr:value("8", translate("N8"))
	bandlist_nr:value("28", translate("N28"))
	bandlist_nr:value("41", translate("N41"))
	bandlist_nr:value("78", translate("N78"))
	bandlist_nr:value("79", translate("N79"))
	bandlist_nr:depends("smode","4")
	bandlist_nr:depends("smode","6")
	bandlist_nr:depends("smode","7")
	
	arfcn = section:taboption("advanced", Value, "arfcn", translate("Arfcn"))
	arfcn:depends("smode","2")
	arfcn:depends("smode","4")
	arfcn.placeholder=translate("[range: 0~4294967295]")
	
	pci = section:taboption("advanced", Value, "pci", translate("PcellId"))
	pci:depends("smode","2")
	pci.placeholder=translate("[range: 0~503]")
	
	psc = section:taboption("advanced", Value, "psc", translate("PcellId"), translate("To lock a cell, specify the frequency band at the same time"))
	psc:depends("smode","4")
	psc.placeholder=translate("[range: 0~1007]")
	
	scs = section:taboption("advanced", ListValue, "scs", translate("SCS"))
	scs:value("0", translate("15kHz"))
	scs:value("1", translate("30kHz"))
	scs:value("2", translate("60kHz"))
	scs:value("3", translate("120kHz"))
	scs:value("4", translate("240kHz"))
	scs.default = "1"
	scs:depends("smode","4")

end

-- smode = section:taboption("advanced", ListValue, "smode", translate("Server Type"))
-- smode.default = "0"
-- smode:value("0", translate"Automatically")
-- smode:value("1", "WCDMA Only")
-- smode:value("2", "LTE Only")
-- smode:value("3", "WCDMA And LTE")
-- if modem_name("sim7600") == "1" then
	-- smode:value("5", "GSM Only")
	-- smode:value("8", "GSM And WCDMA")
	-- smode:value("9", "GSM And LTE")
	-- smode:value("10", "GSM And WCDMA And LTE")
-- else
	-- smode:value("4", "NR5G Only")
	-- smode:value("6", "LTE And NR5G")
	-- smode:value("7", "WCDMA And LTE And NR5G")
-- end


ipv4v6 = section:taboption("advanced", ListValue, "ipv4v6", translate("IP Type"))
ipv4v6:value("IP", "IPV4")
--ipv4v6:value("IPV6", "IPV6")
ipv4v6:value("IPV4V6", "IPV4V6")

if ( modem_name("160") == "1" or modem_name("668-EU") == "1" ) then
	gps = section:taboption("advanced", Flag, "gps_enable", translate("Enable GPS"))
	gps_log = section:taboption("advanced", Flag, "gpslog_enable", translate("Enable GPS Log"))
	gps_log:depends("gps_enable","1")
	gpslog_file = section:taboption("advanced", Value, "gps_path", translate("GPS Log Path"))
	gpslog_file:depends("gpslog_enable","1")
	gpslog_file.default = "/var/log/gps.log"

end

metric = section:taboption("physical", Value, "metric", translate("Metric"))
metric.default = "10"

mtu = section:taboption("physical", Value, "mtu", translate("Override MTU"))
mtu.placeholder = "1500"
mtu.datatype = "max(9200)"

function m.on_after_commit(map)
    io.popen("/etc/init.d/modeminit restart &")
end

return m
