'''

Copyright (C) 2023 Clourney Semiconductor - All Rights Reserved.
SPDX-License-Identifier: BSD-3-Clause
https://spdx.org/licenses

'''

import re
import os
import sys
import ctypes
from pprint import pprint

directory = sys.argv[1]
str_filename = os.path.basename(directory)
filenames = ["clsapi_wifi.h", "clsapi_net.h", "clsapi_sys.h", "clsapi_base.h"]
file_to_generate = "restapi.h"

phases = list()
phases_head = list()
list_functions = list()
restapi_resource = dict()

def contains_keywords(text, keywords):
    return any(keyword in text for keyword in keywords)

# end def

def init(file_name):
	"""
	Purpose: initialize all needed parameters
	"""
	with open(file_name) as f:
		content = f.read().split(r'brief')

	for phase in content:
		if 'int clsapi_' in phase:
			phases.append(phase)
		else :
			phases_head.append(phase)

# end def

def get_members(line, c):
	"""
	Purpose: Get all the members from the lines
	Param [in]: line every line will be parsed
	Param [in]: c the lines generated by iterator
	"""
	struct_start_flag = True
	struct_list = {}

	while True:
		try:
			if "struct" in line or 'union' in line or 'enum' in line:
				if '{' in line:
					if struct_start_flag:
						struct_start_flag = False
						name =	line,
						struct_list[name] = []
					else:
						struct_list[name].append(get_members(line, c))
				else:
					if 'typedef' in line:
						break
					struct_list[name].append(line)
				line = next(c)
			else:
				if not struct_start_flag:
					struct_list[name].append(line)
					if re.search("}.*;", line):
						struct_start_flag = True
						return struct_list
				line = next(c)

		except StopIteration:
			break

	return struct_list
# end def

def parse_code(c_code):
	"""
	Purpose: parse the code into sevel parts of 'struct'/'union'/'enum'
	Param [in]: c_code the codes will be parsed
	"""
	temp_list = []
	struct_list = []
	data_structures = []

	c_code = re.split(r'\n', c_code)
	for line in c_code:
	    if line.startswith('};'):
		    struct_list.append(line)
		    temp_str = '\n'.join(struct_list)
		    data_structures.append(temp_str)
		    struct_list.clear()
	    else:
		    struct_list.append(line)

	pattern = re.compile(r'}.+;')

	if data_structures :
		for struct_block in data_structures:
			lines = str(struct_block).split('\n')
			if pattern.match(lines[-1]):
			    typedef_struct_name = str(lines[-1]).replace('}', '').replace(';', '')
			    lines[0] = str(lines[0]).replace('{', '%s {' %typedef_struct_name)

			c = iter(lines)
			first_line = next(c)
			temp_list.append(get_members(first_line, c))
		return temp_list
	else:
		return None
# end def

def clean_code(input_string):
	"""
	Purpose: Clean all the macro definition or include
	Param [in]: Input_string the code will be deleted from
	Return : The whole string whose definitions were deleted
	"""
	cleaned_string = re.sub(r'#\s*define\s+.*|^\s*#ifdef\s+.*|^\s*#include\s+.*|^\s*#ifndef\s+.*', '', input_string, flags=re.MULTILINE)
	cleaned_string = re.sub(r'\n\s*\n', '\n', cleaned_string)
	lines = cleaned_string.split('\n')
	filtered_lines = []

	for line in lines:
		if not re.match(r'\s*typedef\s+\w+\s+\w+\s*;', line) and '\\' not in line:
			filtered_lines.append(line)

	cleaned_string = '\n'.join(filtered_lines)
	cleaned_string = cleaned_string.strip()
	cleaned_string = cleaned_string.replace(' STRUCT_PACKED', '')
	cleaned_string = cleaned_string.replace('unsigned', '')
	cleaned_string = cleaned_string.replace('long long', 'uint64_t')
	cleaned_string = cleaned_string.replace('long', 'uint64_t')
	cleaned_string = cleaned_string.replace('sa_family_t', 'uint32_t')
	cleaned_string = re.sub(r'\t+', '\t', cleaned_string)
	cleaned_string = cleaned_string.replace('\t', ' ')
	#print(f'{cleaned_string}')
	lines = cleaned_string.splitlines()
	cleaned_lines = lines[:-2]

	return '\n'.join(cleaned_lines)
# end def

def parse_head():
	"""
	Purpose: parse all other the header files
	"""

	heads = ' '.join(phases_head)
	cleaned_string = re.sub(r'/\*.*?\*/', '', heads, flags=re.DOTALL)
	cleaned_string = re.sub(r'//.*', '', cleaned_string)
	heads = clean_code(cleaned_string)
# end def

#{"dhcp_ipv4leases", uh_restf_handle_ubus_get},

def main(filename, restapi_resource):

	for file_name in filenames :
	    matched_files = find_files(directory, file_name)
	    for file in matched_files:
		    parse_file(file)

	class_method = 'static restapi resources[]'
	with open(filename, "r+") as file:
		content = file.readlines()

	flag = 0
	for index, line in enumerate(content):
                if class_method in line:
                        idx = index + 1
                        flag = 1
                if '};' in line:
                        if flag == 1:
                                end_idx = index
                                break

	del content[idx:end_idx]
	for key, value in restapi_resource.items():
		if value == 'get' :
			string = '\t{"' + key + '", ' + 'uh_restf_handle_ubus_get},\n\n'
		elif value == 'post':
			string = '\t{"' + key + '", ' + 'NULL, uh_restf_handle_ubus_post},\n\n'
		elif value == 'delete':
			string = '\t{"' + key + '", ' + 'NULL, NULL, NULL, NULL, uh_restf_handle_ubus_delete},\n\n'
		content.insert(idx, string)
		idx = idx + 1

	string = '\t{"session_login", NULL, uh_restf_handle_ubus_post},\n\n'
	content.insert(idx, string)
	idx = idx + 1

	with open(filename, 'w') as f:
		for item in content:
			f.write(item)
# end def

def parse_file(file_name):
	"""
	Purpose:
		1.parse all the private structures -get all the parameters and their data type
		2.get all the function's name, parameters and so forth
		3.according to the function, splice the strings that needed to form an C expression.
	"""
	init(file_name)
	parse_head()
	global restapi_resource

	for f in phases:
		param_in = re.findall('(?<=param ).*?(?= \[In\])', f)#parameters in comments
		param_out = re.findall('(?<=param ).*?(?= \[Out\])', f)#parameters in comments
		func_name = str(re.findall('int clsapi_[a-zA-Z0-9_]+\(', f))
		func_name = re.sub('int clsapi_|\(', '', func_name).strip('\']').strip('[\'')
		if not func_name:
		    print("ERROR:Invalid function name: invalid prefix ")
		    raise NameError("Example: clsapi_net_set_opmode")
		if 'wifi' not in func_name and  'sys' not in func_name and 'net' not in func_name and 'base' not in func_name:
		    print("ERROR: Invalid function name %s: module name is missing." %func_name)
		    raise NameError("Example: clsapi_net_set_opmode")

		#print(f"function name : {func_name}\tparam_in :{param_in};\t param_out: {param_out}")
		pattern = r'int\s+\w+\s*\(.*?\);'
		params_all = re.findall(pattern, f, re.DOTALL)
		for param in params_all:
			params = str(re.findall(r'\((.*?)\)', param, re.DOTALL))
			params = params.replace('\\n', '').replace('\\t', '')

		list_functions.append('%s' %func_name)
		param_total = params.strip('[').strip(']').strip('\'').rstrip('\)').split(',')
		if param_in :
			i = 0
			for a in param_in:
					p_in = str(a).strip()
					check_params_in = re.sub(r'\*|\[.*?\]|\(|\)', '', param_total[i])
					if p_in not in check_params_in.split(' '):
						print(f'{func_name}- comment: {p_in}, parameter:{param_total[i]}')
						print("ERROR, parameters in comments are not same with which in functions")
						raise NameError("Parameters are not same")

					i = i+1

		if param_out:
			i = 0
			for b in param_out:
					check_params_out = re.sub(r'\*|\[.*?\]|\(|\)', '', param_total[i + len(param_in)])
					if b not in check_params_out.split(' '):
						print(f'{func_name} - comment: {b}, param: {str(param_total[i + len(param_in)])}')
						print(f"ERROR, parameters in comments are not same with which in functions")
						raise NameError("Parameters are not same")
					i = i+1
		#end for loop
		if not param_in :
			restapi_resource[func_name] = "get"
		elif '_del_' in func_name :
			restapi_resource[func_name] = "delete"
		else:
			restapi_resource[func_name] = "post"



# end def

def find_files(directory, file_name):
    result = []

    for root, dirs, files in os.walk(directory):
	    for filename in files:
		    if file_name in filename:
		     result.append(os.path.join(root, filename))

    return result

main(file_to_generate, restapi_resource)
