/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2023 Clourneysemi Corporation. */

#ifndef _SWITCH_L3_H_
#define _SWITCH_L3_H_

#define IP_ROUTE_VRF_NUMBER		2
#define IP_TABLE_HASH_BUCKET_NUMBER	2

enum {
	ROUTER_PORT_MAC_ARG_MACADDRESS,
	ROUTER_PORT_MAC_ARG_MACMASK,
	ROUTER_PORT_MAC_ARG_SELECTMACENTRYPORTMASK,
	ROUTER_PORT_MAC_ARG_ALTMACADDRESS,
	ROUTER_PORT_MAC_ARG_VALID,
	ROUTER_PORT_MAC_ARG_VRF,
};

enum {
	INGRESS_ROUTER_TABLE_ARG_ACCEPTIPV4,
	INGRESS_ROUTER_TABLE_ARG_ACCEPTIPV6,
	INGRESS_ROUTER_TABLE_ARG_ACCEPTMPLS,
	INGRESS_ROUTER_TABLE_ARG_MINTTL,
	INGRESS_ROUTER_TABLE_ARG_MINTTLTOCPU,
	INGRESS_ROUTER_TABLE_ARG_IPV4HITUPDATES,
	INGRESS_ROUTER_TABLE_ARG_IPV6HITUPDATES,
	INGRESS_ROUTER_TABLE_ARG_MPLSHITUPDATES,
	INGRESS_ROUTER_TABLE_ARG_ECMPUSEIPDA,
	INGRESS_ROUTER_TABLE_ARG_ECMPUSEIPSA,
	INGRESS_ROUTER_TABLE_ARG_ECMPUSEIPTOS,
	INGRESS_ROUTER_TABLE_ARG_ECMPUSEIPPROTO,
	INGRESS_ROUTER_TABLE_ARG_ECMPUSEIPL4SP,
	INGRESS_ROUTER_TABLE_ARG_ECMPUSEIPL4DP,
	INGRESS_ROUTER_TABLE_ARG_MMPVALID,
	INGRESS_ROUTER_TABLE_ARG_MMPPTR,
	INGRESS_ROUTER_TABLE_ARG_MMPORDER,
};

enum {
	L3_LPM_RESULT_ARG_USEECMP,
	L3_LPM_RESULT_ARG_ECMPMASK,
	L3_LPM_RESULT_ARG_ECMPSHIFT,
	L3_LPM_RESULT_ARG_NEXTHOPPOINTER,
};

enum {
	HASH_BASED_L3_ROUTING_TABLE_ARG_IPVERSION,
	HASH_BASED_L3_ROUTING_TABLE_ARG_MPLS,
	HASH_BASED_L3_ROUTING_TABLE_ARG_VRF,
	HASH_BASED_L3_ROUTING_TABLE_ARG_DESTIPADDR,
	HASH_BASED_L3_ROUTING_TABLE_ARG_NEXTHOPPOINTER,
	HASH_BASED_L3_ROUTING_TABLE_ARG_USEECMP,
	HASH_BASED_L3_ROUTING_TABLE_ARG_ECMPMASK,
	HASH_BASED_L3_ROUTING_TABLE_ARG_ECMPSHIFT,
};

enum {
	L3_ROUTING_DEFAULT_ARG_NEXTHOP,
	L3_ROUTING_DEFAULT_ARG_PKTDROP,
	L3_ROUTING_DEFAULT_ARG_SENDTOCPU,
};

enum {
	L3_ROUTING_TCAM_ARG_PROTO,
	L3_ROUTING_TCAM_ARG_VRF,
	L3_ROUTING_TCAM_ARG_DESTIPADDR,
	L3_ROUTING_TCAM_ARG_PROTOMASKN,
	L3_ROUTING_TCAM_ARG_VRFMASKN,
	L3_ROUTING_TCAM_ARG_DESTIPADDRMASKN,
	L3_ROUTING_TCAM_ARG_VALID,
};

enum {
	NEXT_HOP_TABLE_ARG_VALIDENTRY,
	NEXT_HOP_TABLE_ARG_SRV6SID,
	NEXT_HOP_TABLE_ARG_NEXTHOPPACKETMOD,
	NEXT_HOP_TABLE_ARG_L2UC,
	NEXT_HOP_TABLE_ARG_DESTPORT_OR_MCADDR,
	NEXT_HOP_TABLE_ARG_PKTDROP,
	NEXT_HOP_TABLE_ARG_SENDTOCPU,
	NEXT_HOP_TABLE_ARG_TUNNELENTRY,
	NEXT_HOP_TABLE_ARG_TUNNELENTRYPTR,
	NEXT_HOP_TABLE_ARG_TUNNELEXIT,
	NEXT_HOP_TABLE_ARG_TUNNELEXITPTR,
};

enum {
	NEXT_HOP_PKT_MOD_ARG_VALID,
	NEXT_HOP_PKT_MOD_ARG_OUTERVLANAPPEND,
	NEXT_HOP_PKT_MOD_ARG_OUTERPCPSEL,
	NEXT_HOP_PKT_MOD_ARG_OUTERCFIDEISEL,
	NEXT_HOP_PKT_MOD_ARG_OUTERETHTYPE,
	NEXT_HOP_PKT_MOD_ARG_OUTERVID,
	NEXT_HOP_PKT_MOD_ARG_OUTERPCP,
	NEXT_HOP_PKT_MOD_ARG_OUTERCFIDEI,
	NEXT_HOP_PKT_MOD_ARG_INNERVLANAPPEND,
	NEXT_HOP_PKT_MOD_ARG_INNERPCPSEL,
	NEXT_HOP_PKT_MOD_ARG_INNERCFIDEISEL,
	NEXT_HOP_PKT_MOD_ARG_INNERETHTYPE,
	NEXT_HOP_PKT_MOD_ARG_INNERVID,
	NEXT_HOP_PKT_MOD_ARG_INNERPCP,
	NEXT_HOP_PKT_MOD_ARG_INNERCFIDEI,
	NEXT_HOP_PKT_MOD_ARG_MSPTPTR,
};

enum {
	NEXT_HOP_DA_MAC_ARG_DAMAC,
};

int switch_l3_config(int argc, char **argv);
void switch_l3_usage(void);
#endif /* _SWITCH_L3_H_ */
