/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2023 Clourneysemi Corporation. */

#ifndef _SWITCH_L2_H_
#define _SWITCH_L2_H_

#define L2_DA_HASH_LOOKUP_TABLE_BUCKET_MAX	4

//L2 DESTINATION TABLE
enum {
	L2_DESTINATION_TABLE_ARG_UC,
	L2_DESTINATION_TABLE_ARG_DESTPORT_OR_MCADDR,
	L2_DESTINATION_TABLE_ARG_PKTDROP,
	L2_DESTINATION_TABLE_ARG_TUNNELENTRY,
	L2_DESTINATION_TABLE_ARG_TUNNELENTRYPTR,
	L2_DESTINATION_TABLE_ARG_TUNNELEXIT,
	L2_DESTINATION_TABLE_ARG_TUNNELEXITPTR,
};

//L2 Lookup Collision Table (Masks)
enum {
	L2_LOOKUP_COLLISION_ARG_MACADDR,
	L2_LOOKUP_COLLISION_ARG_GID,

};

//L2 MULTICAST TABLE
enum {
	L2_MULTICAST_TABLE_ARG_MCPORTMASK,
	L2_MULTICAST_TABLE_ARG_TUNNELENTRY,
	L2_MULTICAST_TABLE_ARG_TUNNELENTRYPTR,
	L2_MULTICAST_TABLE_ARG_TUNNELEXIT,
	L2_MULTICAST_TABLE_ARG_TUNNELEXITPTR,

};

enum {
       L2_AGING_TABLE_ARG_VALID,
       L2_AGING_TABLE_ARG_STAT,
       L2_AGING_TABLE_ARG_HIT,
};

enum {
       L2_AGING_STATUS_SHADOW_TABLE_ARG_VALID,
};

enum {
       L2_AGING_STATUS_SHADOW_TABLE_REPLICA_ARG_VALID,
};

int switch_l2_config(int argc, char **argv);
void switch_l2_usage(void);

#define L2_DEST_TYPE_TABLE		"table"
#define L2_DEST_TYPE_REPLICA		"replica"

#define L2_LOOKUP_ADDR_TYPE_DA		"da"
#define L2_LOOKUP_ADDR_TYPE_SA		"sa"

#define L2_LOOKUP_ACTION_TYPE_ADD	"add"
#define L2_LOOKUP_ACTION_TYPE_DEL	"del"

#define L2_LOOKUP_TYPE_AGING		"aging"
#define L2_LOOKUP_TYPE_SHADOW		"shadow"
#define L2_LOOKUP_TYPE_REPLICA		"replica"

#define L2_COLL_TYPE_TABLE		"table"
#define L2_COLL_TYPE_MASK		"mask"

#define L2_RESERVED_MULTICAST_ADDR_TYPE_DA		"da"
#define L2_RESERVED_MULTICAST_ADDR_TYPE_SA		"sa"

#endif /* _SWITCH_L2_H_ */
