//复位XGMAC
REG_W(XGMAC1_SFT_RST_N, xgmac1_sft_rst_n, 0);			//QSGMII连接XGMAC1/2/3/4
REG_W(XGMAC2_SFT_RST_N, xgmac2_sft_rst_n, 0);			//使用上可只用2个或3个XGMAC
REG_W(XGMAC3_SFT_RST_N, xgmac3_sft_rst_n, 0);
REG_W(XGMAC4_SFT_RST_N, xgmac4_sft_rst_n, 0);

//REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_XS_PCS_CTRL2, PCS_TYPE_SEL, 1);			//KR/10GBASE-R support
//REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_XS_PCS_CTRL1, SS13, 0);					//Dubhe1000不存在，Dubhe2000存在

//!!! 加其他3个
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_AN_CTRL, PCS_MODE, 3);					//配置为QSGMII mode
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_AN_CTRL, MII_CTRL, 0);					//4-bit MII
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_AN_CTRL, MII_AN_INTR_EN, 1);			//CL37 AN Complete Interrupt Enable

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_1_AN_CTRL, PCS_MODE, 3);					//配置为QSGMII mode
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_1_AN_CTRL, MII_CTRL, 0);					//4-bit MII
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_1_AN_CTRL, MII_AN_INTR_EN, 1);			//CL37 AN Complete Interrupt Enable

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_2_AN_CTRL, PCS_MODE, 3);					//配置为QSGMII mode
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_2_AN_CTRL, MII_CTRL, 0);					//4-bit MII
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_2_AN_CTRL, MII_AN_INTR_EN, 1);			//CL37 AN Complete Interrupt Enable

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_3_AN_CTRL, PCS_MODE, 3);					//配置为QSGMII mode
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_3_AN_CTRL, MII_CTRL, 0);					//4-bit MII
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_3_AN_CTRL, MII_AN_INTR_EN, 1);			//CL37 AN Complete Interrupt Enable
//!!!!BIT 9

//MPLL配置
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL0, MPLLA_MULTIPLIER, 32);		//PLL FB divider
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_MPLLA_CTRL3, MPLLA_BANDWIDTH, 41013);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_VCO_CAL_LD0, VCO_LD_VAL_0, 1344);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_VCO_CAL_REF0, VCO_REF_LD_0, 42);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_RX_EQ_CTRL4, CONT_ADAPT_0, 0);		//关闭连续自适应
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_RATE_CTRL, TX0_RATE, 1);			//baud/2
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_RX_RATE_CTRL, RX0_RATE_1_0, 1);			//baud/2
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_TX_GENCTRL2, TX0_WIDTH, 3);				//QSGMII---20bit
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_RX_GENCTRL2, RX0_WIDTH, 3);				//QSGMII---20bit
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL2, MPLLA_DIV16P5_CLK_EN, 0);	//关闭DIV16.5
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL2, MPLLA_DIV10_CLK_EN, 1);		//使能DIV10
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL2, MPLLA_DIV8_CLK_EN, 0);		//关闭DIV8
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_GENCTRL1, VBOOST_EN_0, 0);			//关闭TX Boost

//Serdes RX配置
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL0, CTLE_BOOST_0, 14);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL0, VGA1_GAIN_0, 4);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL0, VGA2_GAIN_0, 4);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL0, CTLE_POLE_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_RX_CDR_CTRL1, VCO_STEP_CTRL_0, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_RX_CDR_CTRL1, VCO_TEMP_COMP_EN_0, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_RX_CDR_CTRL1, VCO_FRQBAND_0, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_MISC_CTRL0, RX0_MISC, 20);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_GENCTRL4, RX_DFE_BYP_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_IQ_CTRL0, RX0_DELTA_IQ, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL5, RX0_ADPT_MODE, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL5, RX_ADPT_PROG_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL5, RX_ADPT_SEL_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_GENCTRL1, TX_CLK_RDY_0, 0);		//指示TX input clock Ready

VR_RST(xpcs_num);

//配置TX FFE
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_GENCTRL1, TX_CLK_RDY_0, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_EQ_CTRL0, TX_EQ_MAIN, 36);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_EQ_CTRL0, TX_EQ_PRE, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_EQ_CTRL1, TX_EQ_POST_2, 0);
//REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_EQ_CTRL1, TX_EQ_OVR_RIDE, 1);		//不支持CL72，不需要配置

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_DIG_CTRL1, MAC_AUTO_SW, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_MII_CTRL, AN_ENABLE, 1);

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_1_DIG_CTRL1, MAC_AUTO_SW, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_MII_1_CTRL, AN_ENABLE, 1);

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_2_DIG_CTRL1, MAC_AUTO_SW, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_MII_2_CTRL, AN_ENABLE, 1);

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_3_DIG_CTRL1, MAC_AUTO_SW, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_MII_3_CTRL, AN_ENABLE, 1);

printf("===>解复位XGMAC\n");
REG_W(XGMAC1_SFT_RST_N, xgmac1_sft_rst_n, 1);			//和复位XGMAC对应
REG_W(XGMAC2_SFT_RST_N, xgmac2_sft_rst_n, 1);
REG_W(XGMAC3_SFT_RST_N, xgmac3_sft_rst_n, 1);
REG_W(XGMAC4_SFT_RST_N, xgmac4_sft_rst_n, 1);
