if (!xpcs_num)
REG_W(XGMAC0_SFT_RST_N, xgmac0_sft_rst_n, 0);		//
else
REG_W(XGMAC0_SFT_RST_N, xgmac1_sft_rst_n, 0);		//

REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_XS_PCS_CTRL2, PCS_TYPE_SEL, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_AN_CTRL, MII_CTRL, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_AN_CTRL, TX_CONFIG, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_AN_CTRL, PCS_MODE, 2);

if (serdes_mode == HSGMII_EM) {
	REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_XS_PCS_CTRL1, SS13, 0);
}
//配置PCS工作模式
//TO_DO
if (serdes_mode == HSGMII_EM) { //2.5G SGMII+
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL0, MPLLA_MULTIPLIER, 40);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_MPLLA_CTRL3, MPLLA_BANDWIDTH, 40983);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_VCO_CAL_LD0, VCO_LD_VAL_0, 1360);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_VCO_CAL_REF0, VCO_REF_LD_0, 34);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_RATE_CTRL, TX0_RATE, 2);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_RX_RATE_CTRL, RX0_RATE_1_0, 2);
}
else { //1G SGMII
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL0, MPLLA_MULTIPLIER, 32);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_MPLLA_CTRL3, MPLLA_BANDWIDTH, 41022);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_VCO_CAL_LD0, VCO_LD_VAL_0, 1344);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_VCO_CAL_REF0, VCO_REF_LD_0, 42);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_RATE_CTRL, TX0_RATE, 3);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_RX_RATE_CTRL, RX0_RATE_1_0, 3);
}

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_RX_EQ_CTRL4, CONT_ADAPT_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_TX_GENCTRL2, TX0_WIDTH, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_RX_GENCTRL2, RX0_WIDTH, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL2, MPLLA_DIV16P5_CLK_EN, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL2, MPLLA_DIV10_CLK_EN, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_MPLLA_CTRL2, MPLLA_DIV8_CLK_EN, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_GENCTRL1, VBOOST_EN_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_GENCTRL1, TX_CLK_RDY_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL0, CTLE_BOOST_0, 14);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL0, VGA1_GAIN_0, 4);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL0, VGA2_GAIN_0, 4);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL0, CTLE_POLE_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_RX_CDR_CTRL1, VCO_STEP_CTRL_0, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_RX_CDR_CTRL1, VCO_TEMP_COMP_EN_0, 1);

if (serdes_mode == HSGMII_EM) { //2.5G SGMII+
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_RX_CDR_CTRL1, VCO_FRQBAND_0, 10);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_MISC_CTRL0, RX0_MISC, 23);
}
else {
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_RX_CDR_CTRL1, VCO_FRQBAND_0, 1);
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_MISC_CTRL0, RX0_MISC, 22);
}

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_GENCTRL4, RX_DFE_BYP_0, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_IQ_CTRL0, RX0_DELTA_IQ, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL5, RX0_ADPT_MODE, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL5, RX_ADPT_PROG_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_16G_25G_RX_EQ_CTRL5, RX_ADPT_SEL_0, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_REF_CLK_CTRL, REF_RPT_CLK_EN, 1);

//phy soft reset
if(serdes_mode == HSGMII_EM) {//2.5G SGMII+
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PCS_DIG_CTRL1, EN_2_5G_MODE, 1);
} else { 
	REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PCS_DIG_CTRL1, EN_2_5G_MODE, 0);
}

VR_RST(xpcs_num);

REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_GENCTRL1, TX_CLK_RDY_0, 1);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_EQ_CTRL0, TX_EQ_MAIN, 40);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_EQ_CTRL0, TX_EQ_PRE, 0);
REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_XS_PMA_MP_12G_16G_25G_TX_EQ_CTRL1, TX_EQ_POST_1, 0);

//REG_W(XPCS_BASE_ADDR(xpcs_num) + VR_MII_DIG_CTRL1, MAC_AUTO_SW, 1);
//REG_W(XPCS_BASE_ADDR(xpcs_num) + SR_MII_CTRL, AN_ENABLE, 1);

if (!xpcs_num)
REG_W(XGMAC0_SFT_RST_N, xgmac0_sft_rst_n, 1);
else
REG_W(XGMAC0_SFT_RST_N, xgmac1_sft_rst_n, 1);
