#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

#START=99

start()
{	
	nss_queue0=$(cat /proc/interrupts | grep nss_queue0 | sed -n 1p | awk -F ':' '{print$1}' | awk '{print$1}')
	xhci_hcd_usb1=$(cat /proc/interrupts | grep xhci-hcd:usb1 | sed -n 1p | awk -F ':' '{print$1}' | awk '{print$1}')
	nss_empty_buf_queue=$(cat /proc/interrupts | grep nss_empty_buf_queue | awk -F ':' '{print$1}' | awk '{print$1}')
	ce1=$(cat /proc/interrupts | grep ce1 | sed -n 1p | awk -F ':' '{print$1}' | awk '{print$1}')
	ce2=$(cat /proc/interrupts | grep ce2 | sed -n 1p | awk -F ':' '{print$1}' | awk '{print$1}')
	if [ $(lsmod | grep pcie_mhi | wc -l) -eq 1 ] && [ -n "$(ifconfig -a | grep rmnet_mhi0)" ];then
		echo 4 > /sys/class/net/rmnet_mhi0.1/queues/rx-0/rps_cpus 
		echo 2 > /sys/class/net/rmnet_mhi0/queues/rx-0/rps_cpus 
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 

		tc qdisc add dev br-lan root nsspfifo limit 2048 accel_mode 0 set_default

		echo 8 > /proc/irq/$nss_queue0/smp_affinity
		echo 4 > /proc/irq/$xhci_hcd_usb1/smp_affinity
		echo 2 > /proc/irq/$nss_empty_buf_queue/smp_affinity
		#新增
		echo 4 > /proc/irq/$ce1/smp_affinity 
		echo 8 > /proc/irq/$ce2/smp_affinity
		###
		echo 10000 > /proc/sys/net/core/netdev_max_backlog
		
		echo "/sys/class/net/rmnet_mhi0.1/queues/rx-0/rps_cpus $(cat /sys/class/net/rmnet_mhi0.1/queues/rx-0/rps_cpus)" >> /tmp/log/set_usb.log
		echo "/sys/class/net/rmnet_mhi0/queues/rx-0/rps_cpus $(cat /sys/class/net/rmnet_mhi0/queues/rx-0/rps_cpus)" >> /tmp/log/set_usb.log
		echo "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)" >> /tmp/log/set_usb.log
		echo "nss_queue0 /proc/irq/$nss_queue0/smp_affinity $(cat /proc/irq/$nss_queue0/smp_affinity)" >> /tmp/log/set_usb.log
		echo "xhci-hcd:usb1 /proc/irq/$xhci_hcd_usb1/smp_affinity $(cat /proc/irq/$xhci_hcd_usb1/smp_affinity)" >> /tmp/log/set_usb.log
		echo "nss_empty_buf_queue /proc/irq/$nss_empty_buf_queue/smp_affinity $(cat /proc/irq/$nss_empty_buf_queue/smp_affinity)" >> /tmp/log/set_usb.log
		echo "ce1 /proc/irq/$ce1/smp_affinity $(cat /proc/irq/$ce1/smp_affinity)" >> /tmp/log/set_usb.log
		echo "ce2 /proc/irq/$ce2/smp_affinity $(cat /proc/irq/$ce2/smp_affinity)" >> /tmp/log/set_usb.log
		echo "/proc/sys/net/core/netdev_max_backlog $(cat /proc/sys/net/core/netdev_max_backlog)" >> /tmp/log/set_usb.log
		
	elif [ -n "$(ifconfig -a | grep pcie_mhi0)" ];then
		echo 4 > /sys/class/net/pcie_mhi0.1/queues/rx-0/rps_cpus 
		echo 2 > /sys/class/net/pcie_mhi0/queues/rx-0/rps_cpus 
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 

		tc qdisc add dev br-lan root nsspfifo limit 2048 accel_mode 0 set_default

		echo 8 > /proc/irq/$nss_queue0/smp_affinity
		echo 4 > /proc/irq/$xhci_hcd_usb1/smp_affinity
		echo 2 > /proc/irq/$nss_empty_buf_queue/smp_affinity
		#新增
		echo 4 > /proc/irq/$ce1/smp_affinity 
		echo 8 > /proc/irq/$ce2/smp_affinity
		###
		echo 10000 > /proc/sys/net/core/netdev_max_backlog
			
		echo "/sys/class/net/pcie_mhi0.1/queues/rx-0/rps_cpus $(cat /sys/class/net/pcie_mhi0.1/queues/rx-0/rps_cpus)" >> /tmp/log/set_usb.log
		echo "/sys/class/net/pcie_mhi0/queues/rx-0/rps_cpus $(cat /sys/class/net/pcie_mhi0/queues/rx-0/rps_cpus)" >> /tmp/log/set_usb.log
		echo "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)" >> /tmp/log/set_usb.log
		echo "nss_queue0 /proc/irq/$nss_queue0/smp_affinity $(cat /proc/irq/$nss_queue0/smp_affinity)" >> /tmp/log/set_usb.log
		echo "xhci-hcd:usb1 /proc/irq/$xhci_hcd_usb1/smp_affinity $(cat /proc/irq/$xhci_hcd_usb1/smp_affinity)" >> /tmp/log/set_usb.log
		echo "nss_empty_buf_queue /proc/irq/$nss_empty_buf_queue/smp_affinity $(cat /proc/irq/$nss_empty_buf_queue/smp_affinity)" >> /tmp/log/set_usb.log
		echo "ce1 /proc/irq/$ce1/smp_affinity $(cat /proc/irq/$ce1/smp_affinity)" >> /tmp/log/set_usb.log
		echo "ce2 /proc/irq/$ce2/smp_affinity $(cat /proc/irq/$ce2/smp_affinity)" >> /tmp/log/set_usb.log
		echo "/proc/sys/net/core/netdev_max_backlog $(cat /proc/sys/net/core/netdev_max_backlog)" >> /tmp/log/set_usb.log
	elif [ -n "$(ifconfig -a | grep usb0)" ] ;then
		echo 4 > /sys/class/net/usb0/queues/rx-0/rps_cpus 
		if [ -n "$(ifconfig -a | grep usb1)" ] ;then
			echo 4 > /sys/class/net/usb1/queues/rx-0/rps_cpus 
		fi
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 

		tc qdisc add dev br-lan root nsspfifo limit 2048 accel_mode 0 set_default

		echo 8 > /proc/irq/$nss_queue0/smp_affinity
		echo 2 > /proc/irq/$xhci_hcd_usb1/smp_affinity
		echo 2 > /proc/irq/$nss_empty_buf_queue/smp_affinity
		echo 4 > /proc/irq/$ce1/smp_affinity
		echo 8 > /proc/irq/$ce2/smp_affinity
		echo 10000 > /proc/sys/net/core/netdev_max_backlog
		
		echo "/sys/class/net/usb0/queues/rx-0/rps_cpus $(cat /sys/class/net/usb0/queues/rx-0/rps_cpus)" >> /tmp/log/set_usb.log
		if [ -n "$(ifconfig -a | grep usb1)" ] ;then
			echo "/sys/class/net/usb1/queues/rx-0/rps_cpus $(cat /sys/class/net/usb1/queues/rx-0/rps_cpus)" >> /tmp/log/set_usb.log
		fi
		echo "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)" >> /tmp/log/set_usb.log
		echo "nss_queue0 /proc/irq/$nss_queue0/smp_affinity $(cat /proc/irq/$nss_queue0/smp_affinity)" >> /tmp/log/set_usb.log
		echo "xhci-hcd:usb1 /proc/irq/$xhci_hcd_usb1/smp_affinity $(cat /proc/irq/$xhci_hcd_usb1/smp_affinity)" >> /tmp/log/set_usb.log
		echo "nss_empty_buf_queue /proc/irq/$nss_empty_buf_queue/smp_affinity $(cat /proc/irq/$nss_empty_buf_queue/smp_affinity)" >> /tmp/log/set_usb.log
		echo "ce1 /proc/irq/$ce1/smp_affinity $(cat /proc/irq/$ce1/smp_affinity)" >> /tmp/log/set_usb.log
		echo "ce2 /proc/irq/$ce2/smp_affinity $(cat /proc/irq/$ce2/smp_affinity)" >> /tmp/log/set_usb.log
		echo "/proc/sys/net/core/netdev_max_backlog $(cat /proc/sys/net/core/netdev_max_backlog)" >> /tmp/log/set_usb.log
	elif [ -n "$(ifconfig -a | grep wwan0)" ] && [ -n "$(ifconfig | grep wwan0_1)" ] ;then
		echo 4 > /sys/class/net/wwan0_1/queues/rx-0/rps_cpus 
		echo 2 > /sys/class/net/wwan0/queues/rx-0/rps_cpus 
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 

		tc qdisc add dev br-lan root nsspfifo limit 2048 accel_mode 0 set_default

		echo 8 > /proc/irq/$nss_queue0/smp_affinity
		echo 2 > /proc/irq/$xhci_hcd_usb1/smp_affinity
		echo 2 > /proc/irq/$nss_empty_buf_queue/smp_affinity
		echo 4 > /proc/irq/$ce1/smp_affinity
		echo 8 > /proc/irq/$ce2/smp_affinity
		echo 10000 > /proc/sys/net/core/netdev_max_backlog
		
		echo "/sys/class/net/wwan0_1/queues/rx-0/rps_cpus $(cat /sys/class/net/wwan0_1/queues/rx-0/rps_cpus)" >> /tmp/log/set_usb.log
		echo "/sys/class/net/wwan0/queues/rx-0/rps_cpus $(cat /sys/class/net/wwan0/queues/rx-0/rps_cpus)" >> /tmp/log/set_usb.log
		echo "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)" >> /tmp/log/set_usb.log
		echo "nss_queue0 /proc/irq/$nss_queue0/smp_affinity $(cat /proc/irq/$nss_queue0/smp_affinity)" >> /tmp/log/set_usb.log
		echo "xhci-hcd:usb1 /proc/irq/$xhci_hcd_usb1/smp_affinity $(cat /proc/irq/$xhci_hcd_usb1/smp_affinity)" >> /tmp/log/set_usb.log
		echo "nss_empty_buf_queue /proc/irq/$nss_empty_buf_queue/smp_affinity $(cat /proc/irq/$nss_empty_buf_queue/smp_affinity)" >> /tmp/log/set_usb.log
		echo "ce1 /proc/irq/$ce1/smp_affinity $(cat /proc/irq/$ce1/smp_affinity)" >> /tmp/log/set_usb.log
		echo "ce2 /proc/irq/$ce2/smp_affinity $(cat /proc/irq/$ce2/smp_affinity)" >> /tmp/log/set_usb.log
		echo "/proc/sys/net/core/netdev_max_backlog $(cat /proc/sys/net/core/netdev_max_backlog)" >> /tmp/log/set_usb.log
	fi
}