#!/bin/sh /etc/rc.common
START=30
USE_PROCD=1
#STOP=10
#USE_PROCD=0
BIN=dialing
kill_exe()
{	
	if [ $(pgrep -f "$1" | wc -l) -ne 0 ];then
		echo $(pgrep -f "$1")
		kk=$(pgrep -f "$1")
		echo $kk
		kill -9 $kk
	fi
}

start_dial()
{
	procd_open_instance
	if [ -n "$1" ];then
		procd_set_param command $BIN $1
	else
		procd_set_param command $BIN
	fi
	procd_set_param respawn
	procd_close_instance
}

config_cellular()
{
	uci -q set cellular.$1.CPIN="+CPIN: SIM IS BUSY"
	uci -q set cellular.$1.CPSI="+CPSI:  "
	uci -q set cellular.$1.BAND="+BAND:  "
	uci -q set cellular.$1.C5GREG="+5GREG:  "
	uci delete cellular.$1.ARFCN="+ARFCN:  "
	uci delete cellular.$1.PCI="+PCI:  "
	uci delete cellular.$1.eNB="+eNB:  "
	uci delete cellular.$1.cellID="+cellID:  "
	uci -q set cellular.$1.SVAL="+SVAL: 0"
	uci -q set cellular.$1.RSRP="+RSRP: 0"
	uci -q set cellular.$1.RSRQ="+RSRQ: 0"
	uci -q set cellular.$1.RSSI="+RSSI: 0"
	uci -q set cellular.$1.SINR="+SINR: 0"
	uci -q set cellular.$1.CSQ="+CSQ: 0"
	uci -q set cellular.$1.COPS="+COPS:  "
	uci -q set cellular.$1.CEREG="+CEREG: "
	uci -q set cellular.$1.CGREG="+CGREG: "
	uci -q set cellular.$1.CGREG="+C5GREG: "
	uci -q set cellular.$1.CCID="+CCID:  "
	uci -q set cellular.$1.IMSI="+IMSI:  "
	uci -q set cellular.$1.SLOT="+SLOT:  "
	uci commit cellular
}


start_service()
{
	echo "b" > /tmp/heartbeat_file
	if [ -n "$1" ];then
		config_cellular $1
		start_dial $1
	else
		if [ -n "$(uci -q get modem.@default[0])" ];then
			config_cellular SIM
			start_dial
		fi
		if [ -n "$(uci -q get modem.SIM)" ];then
			config_cellular SIM
			start_dial
		fi
		if [ -n "$(uci -q get modem.SIM1)" ];then
			config_cellular SIM1
			start_dial SIM1
		fi
		if [ -n "$(uci -q get modem.SIM2)" ];then
			config_cellular SIM2
			start_dial SIM2
		fi
	fi
}

stop_service() {
	if [ -n "$1" ]; then
		if [ "$1" == "SIM1" ];then
			kill_exe quectel-CM
		fi
		kill_exe "$BIN $1"
		ifdown $1
		sleep 1s
		ifup $1
		rm -rf /tmp/*$1
	else
		kill_exe quectel-CM
		if [ -n "$(uci -q get modem.@default[0])" ];then
			ifdown SIM
			sleep 1s
			ifup SIM
			rm -rf /tmp/*SIM
		fi
		if [ -n "$(uci -q get modem.SIM)" ];then
			ifdown SIM
			sleep 1s
			ifup SIM
			rm -rf /tmp/*SIM
		fi
		if [ -n "$(uci -q get modem.SIM1)" ];then
			ifdown SIM1
			sleep 1s
			ifup SIM1
			rm -rf /tmp/*SIM1
		fi
		if [ -n "$(uci -q get modem.SIM2)" ];then
			ifdown SIM2
			sleep 1s
			ifup SIM2
			rm -rf /tmp/*SIM2
		fi
	fi
}
