#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 3.0 .
# Support simcom, Siemens, fibocom dialing

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Supports dial 4/5G within 2 modules, or 1 module via 2 different apns.
LUCI_DEPENDS:=+sendat
PKG_VERSION:=3.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
