obj-y += 	dal_phy.o \
	dal_waMon.o \
	hwp.o \
	hwp_init.o \
	identify.o \
	memory.o \
	miim.o \
	miim_common_drv.o \
	miim_debug.o \
	phy.o \
	phy_common.o \
	phy_construct.o \
	phy_driver_hwp.o \
	phy_experimental_rtl8211fs.o \
	phy_hal.o \
	phy_init.o \
	phy_misc.o \
	phy_patch.o \
	phy_probe.o \
	phy_rtl8218b.o \
	phy_rtl8218b_patch.o \
	phy_rtl826xb.o \
	phy_rtl826xb_patch.o \
	phy_macsec.o \
	aes.o \
	phy_wrapped_miim.o \
	rt_bitop.o \
	sem.o \
	thread.o \
	phy_driver.o \
	time.o  \
	phy_rtl8226.o \
	nic_rtl8226.o \
    	nic_rtl8226b.o \
    	nic_rtl8226_init.o \
    	nic_rtl8226b_init.o \
    	nic_rtl8226_port.o \
	phy_rtl8224.o \
	phy_rtl8224_patch.o
#phy_test.o 
#  cmd.o 
#ccflags-y += -DPHY_ONLY -DCONFIG_SDK_RTL8218B -DCONFIG_SDK_RTL8214FC -I$(srctree)/drivers/net/clourney/rtl8214fc/inc/module -I$(srctree)/drivers/net/clourney/rtl8214fc/inc/module/phy/inc  -I$(srctree)/drivers/net/clourney/rtl8214fc/inc/sdk -I$(srctree)/drivers/net/clourney/rtl8214fc/inc/sdk/include -I$(srctree)/drivers/net/clourney/rtl8214fc/inc/sdk/system/include 
ccflags-y += -DPHY_ONLY -DCONFIG_SDK_WORDSIZE_64 -DCONFIG_SDK_RTL8226 -DCONFIG_SDK_RTL8218B -DCONFIG_SDK_RTL8214FC -I$(srctree)/drivers/net/clourney/rtlphy_sdk/inc 
