# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_NET_DSA_MOTORCOMM) += motorcomm_tag.o
motorcomm_tag-objs			:= motorcomm_mdio.o yt921x.o
obj-$(CONFIG_NET_DSA_VLAN_MOTORCOMM) += motorcomm_vlan_tag.o
motorcomm_vlan_tag-objs			:= motorcomm_mdio.o yt921x.o