obj-y +=    rtl8367_cmd.o \
			ptp.o	\
			trunk.o	\
			eee.o	\
			leaky.o	\
			chip.o	\
			port.o	\
			gpio.o	\
			svlan.o	\
			i2c.o	\
			dot1x.o	\
			rtk_switch.o	\
			qos.o	\
			vlan.o	\
			mirror.o	\
			interrupt.o	\
			rldp.o	\
			l2.o	\
			stat.o	\
			igmp.o	\
			oam.o	\
			acl.o	\
			cpu.o	\
			rate.o	\
			trap.o	\
			led.o	\
			storm.o

ccflags-y += -DCONFIG_DAL_RTL8367D -DMDC_MDIO_OPERATION -I$(srctree)/drivers/net/clourney/rtl8367/

obj-y += dal/
