#!/bin/sh /etc/rc.common
#
# Copyright (c) 2021-2024, Clourney Semiconductor. All rights reserved.
#
# This software and/or documentation is licensed by Clourney Semiconductor under limited terms and conditions.
# Reproduction and redistribution in binary or source form, with or without modification,
# for use solely in conjunction with a Clourney Semiconductor chipset, is permitted in condition which
# must retain the above copyright notice.
#
# By using this software and/or documentation, you agree to the limited terms and conditions.

START=98
USE_PROCD=1
CLASSIC_QOS=/usr/sbin/cls-qos

start_service() {
    $CLASSIC_QOS start
}

stop_service() {
    $CLASSIC_QOS stop
}

service_triggers() {
    procd_add_reload_trigger cls-qos
}

reload_service() {
    $CLASSIC_QOS restart
}

boot() {
    ubus call clsqos start
    start
}
