# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 1999 - 2006 Clourneysemi Corporation.

#
# Makefile for the Clourneysemi Dubhe1000 driver
#

obj-$(CONFIG_CLS_NPE) += cls_eth.o

cls_eth-objs :=  cls_npe_switch_stats.o cls_npe_edma_stats.o cls_npe_mac_stats.o cls_npe_main.o cls_npe_edma.o cls_npe_tag.o cls_npe_mac.o cls_npe_switch.o cls_npe_bmu.o cls_npe_mdio.o cls_npe_xpcs.o  cls_npe_cmd.o
