/*
 * Copyright (c) 2021-2024, Clourney Semiconductor. All rights reserved.
 *
 * This software and/or documentation is licensed by Clourney Semiconductor under limited terms and conditions.
 * Reproduction and redistribution in binary or source form, with or without modification,
 * for use solely in conjunction with a Clourney Semiconductor chipset, is permitted in condition which
 * must retain the above copyright notice.
 *
 * By using this software and/or documentation, you agree to the limited terms and conditions.
 */

/* Modeled on trace-events-sample.h */

/* The trace subsystem name for dubhe1000 will be "dubhe1000".
 *
 * This file is named dubhe1000_trace.h.
 *
 * Since this include file's name is different from the trace
 * subsystem name, we'll have to define TRACE_INCLUDE_FILE at the end
 * of this file.
 */
#undef TRACE_SYSTEM
#define TRACE_SYSTEM dubhe1000

/* See trace-events-sample.h for a detailed description of why this
 * guard clause is different from most normal include files.
 */
#if !defined(_DUBHE1000_TRACE_H_) || defined(TRACE_HEADER_MULTI_READ)
#define _DUBHE1000_TRACE_H_

#include <linux/tracepoint.h>

/*
 * dubhe1000_trace() macro enables shared code to refer to trace points
 * like:
 *
 * trace_dubhe1000{,vf}_example(args...)
 *
 * ... as:
 *
 * dubhe1000_trace(example, args...)
 *
 * ... to resolve to the PF or VF version of the tracepoint without
 * ifdefs, and to allow tracepoints to be disabled entirely at build
 * time.
 *
 * Trace point should always be referred to in the driver via this
 * macro.
 *
 * Similarly, dubhe1000_trace_enabled(trace_name) wraps references to
 * trace_dubhe1000{,vf}_<trace_name>_enabled() functions.
 */
#define _DUBHE1000_TRACE_NAME(trace_name) (trace_ ## dubhe1000 ## _ ## trace_name)
#define DUBHE1000_TRACE_NAME(trace_name) _DUBHE1000_TRACE_NAME(trace_name)

#define dubhe1000_trace(trace_name, args...) DUBHE1000_TRACE_NAME(trace_name)(args)

#define dubhe1000_trace_enabled(trace_name) DUBHE1000_TRACE_NAME(trace_name##_enabled)()

/* Events common to PF and VF. Corresponding versions will be defined
 * for both, named trace_dubhe1000_* and trace_dubhe1000vf_*. The dubhe1000_trace()
 * macro above will select the right trace point name for the driver
 * being built from shared code.
 */

/* Events related to a vsi & ring */
DECLARE_EVENT_CLASS(
	dubhe1000_tx_template,

	TP_PROTO(struct dubhe1000_tx_ring *ring,
		 struct dubhe1000_tx_buffer *buf),

	TP_ARGS(ring, buf),

	/* The convention here is to make the first fields in the
	 * TP_STRUCT match the TP_PROTO exactly. This enables the use
	 * of the args struct generated by the tplist tool (from the
	 * bcc-tools package) to be used for those fields. To access
	 * fields other than the tracepoint args will require the
	 * tplist output to be adjusted.
	 */
	TP_STRUCT__entry(
		__field(void*, ring)
		__field(void*, buf)
	),

	TP_fast_assign(
		__entry->ring = ring;
		__entry->buf = buf;
	),

	TP_printk(
		"ring: %pxbuf %px",
		__entry->ring,
		__entry->buf)
);

DEFINE_EVENT(
	dubhe1000_tx_template, dubhe1000_clean_tx_irq,
	TP_PROTO(struct dubhe1000_tx_ring *ring,
		 struct dubhe1000_tx_buffer *buf),

	TP_ARGS(ring, buf));

DEFINE_EVENT(
	dubhe1000_tx_template, dubhe1000_clean_tx_irq_unmap,
	TP_PROTO(struct dubhe1000_tx_ring *ring,
		 struct dubhe1000_tx_buffer *buf),

	TP_ARGS(ring, buf));

DECLARE_EVENT_CLASS(
	dubhe1000_rx_template,

	TP_PROTO(struct dubhe1000_rx_ring *ring,
		 struct sk_buff *skb),

	TP_ARGS(ring, skb),

	TP_STRUCT__entry(
		__field(struct dubhe1000_rx_ring*, ring)
		__field(struct sk_buff*, skb)
	),

	TP_fast_assign(
		__entry->ring = ring;
		__entry->skb = skb;
	),

	TP_printk(
		"ring: (%px next_to_use %d next_to_clean %d rxbuf.data %px) skb (%px head %px data %px len %d data-len %d tail %d end %d)",
		__entry->ring,
		__entry->ring->next_to_use,
		__entry->ring->next_to_clean,
		__entry->ring->buffer_info->rxbuf.data,
		__entry->skb,
		__entry->skb->head,
		__entry->skb->data,
		__entry->skb->len,
		__entry->skb->data_len,
		__entry->skb->tail,
		__entry->skb->end)
);

DEFINE_EVENT(
	dubhe1000_rx_template, dubhe1000_clean_rx_irq,
	TP_PROTO(struct dubhe1000_rx_ring *ring,
		 struct sk_buff *skb),

	TP_ARGS(ring, skb));

DEFINE_EVENT(
	dubhe1000_rx_template, dubhe1000_clean_rx_irq_rx,
	TP_PROTO(struct dubhe1000_rx_ring *ring,
		 struct sk_buff *skb),

	TP_ARGS(ring, skb));

DECLARE_EVENT_CLASS(
	dubhe1000_xmit_template,

	TP_PROTO(struct sk_buff *skb,
	     struct net_device *netdev,
		 struct dubhe1000_tx_ring *ring),

	TP_ARGS(skb, netdev, ring),

	TP_STRUCT__entry(
		__field(struct sk_buff*, skb)
		__field(struct dubhe1000_tx_ring*, ring)
		__string(devname, netdev->name)
	),

	TP_fast_assign(
		__entry->skb = skb;
		__entry->ring = ring;
		__assign_str(devname, netdev->name);
	),

	TP_printk(
		"netdev: %s skb: (%px head %px data %px len %d data-len %d tail %d end %d) ring: (%px next_to_use %d next_to_clean %d buffer_info(skb %px length %d next_to_watch %d)",
		__get_str(devname),
		__entry->skb,
		__entry->skb->head,
		__entry->skb->data,
		__entry->skb->len,
		__entry->skb->data_len,
		__entry->skb->tail,
		__entry->skb->end,
		__entry->ring,
		__entry->ring->next_to_use,
		__entry->ring->next_to_clean,
		__entry->ring->buffer_info->skb,
		__entry->ring->buffer_info->length,
		__entry->ring->buffer_info->next_to_watch
		)
);

DEFINE_EVENT(
	dubhe1000_xmit_template, dubhe1000_xmit_frame,
	TP_PROTO(struct sk_buff *skb,
	     struct net_device *netdev,
		 struct dubhe1000_tx_ring *ring),

	TP_ARGS(skb, netdev, ring));

DEFINE_EVENT(
	dubhe1000_xmit_template, dubhe1000_xmit_frame_ring,
	TP_PROTO(struct sk_buff *skb,
	     struct net_device *netdev,
		 struct dubhe1000_tx_ring *ring),

	TP_ARGS(skb, netdev, ring));

DEFINE_EVENT(
	dubhe1000_xmit_template, dubhe1000_xmit_frame_ring_drop,
	TP_PROTO(struct sk_buff *skb,
	     struct net_device *netdev,
		 struct dubhe1000_tx_ring *ring),

	TP_ARGS(skb, netdev, ring));

/* Events unique to the PF. */

#endif /* _DUBHE1000_TRACE_H_ */
/* This must be outside ifdef _DUBHE1000_TRACE_H */

/* This trace include file is not located in the .../include/trace
 * with the kernel tracepoint definitions, because we're a loadable
 * module.
 */
#undef TRACE_INCLUDE_PATH
#undef TRACE_INCLUDE_FILE
#define TRACE_INCLUDE_PATH .
#define TRACE_INCLUDE_FILE dubhe2000_trace
#include <trace/define_trace.h>
