/*
 * Copyright (c) 2021-2024, Clourney Semiconductor. All rights reserved.
 *
 * This software and/or documentation is licensed by Clourney Semiconductor under limited terms and conditions.
 * Reproduction and redistribution in binary or source form, with or without modification,
 * for use solely in conjunction with a Clourney Semiconductor chipset, is permitted in condition which
 * must retain the above copyright notice.
 *
 * By using this software and/or documentation, you agree to the limited terms and conditions.
 */

/* dubhe1000_switch.h
 * Structures, enums, and macros for the Switch
 */

#ifndef _DUBHE1000_SWITCH_REGS_H_
#define _DUBHE1000_SWITCH_REGS_H_

#include "dubhe2000.h"
#include "dubhe2000_switch_stats.h"
#include "dubhe2000_switch_conf.h"

/* Global Register */
#define MAC_RX_MAX_PACKET_LEN_TBL                           MAC_RX_MAXIMUM_PACKET_LENGTH
#define MAC_RX_MAX_PACKET_LEN_TBL_MAX                       MAC_RX_MAXIMUM_PACKET_LENGTH_MAX

#define INGRESS_ADMISSION_CTRL_RESET                        INGRESS_ADMISSION_CONTROL_RESET
#define INGRESS_ADMISSION_CTRL_RESET_MAX                    INGRESS_ADMISSION_CONTROL_RESET_MAX

#define INGR_ADMIS_CTRL_TOKEN_BUCKET_CONF                   INGRESS_ADMISSION_CONTROL_TOKEN_BUCKET_CONFIGURATION
#define INGR_ADMIS_CTRL_TOKEN_BUCKET_CONF_MAX               INGRESS_ADMISSION_CONTROL_TOKEN_BUCKET_CONFIGURATION_MAX
#define INGR_ADMIS_CTRL_TOKEN_BUCKET_CONF_ADDR_PER_ENTRY    INGRESS_ADMISSION_CONTROL_TOKEN_BUCKET_CONFIGURATION_ADDR_PER_ENTRY

#define SOURCE_PORT_TBL                                     SOURCE_PORT_TABLE
#define SOURCE_PORT_TBL_MAX                                 SOURCE_PORT_TABLE_MAX
#define SOURCE_PORT_NUM_ADDR_PER_ENTRY                      SOURCE_PORT_TABLE_ADDR_PER_ENTRY

/* L2 Protocol */
#define BOOTP_DHCP_PACKET_DECODER_OPTIONS                   BOOTP_AND_DHCP_PACKET_DECODER_OPTIONS
#define L2_1588_PACKET_DECODER_OPTIONS                      IEEE_1588_L2_PACKET_DECODER_OPTIONS
#define L4_1588_PACKET_DECODER_OPTIONS                      IEEE_1588_L4_PACKET_DECODER_OPTIONS
#define EAPOL_PACKET_DECODER_OPTIONS                        IEEE_802_1X_AND_EAPOL_PACKET_DECODER_OPTIONS

/* L2 Table/Register */
#define L2_DESTINATION_TBL					L2_DESTINATION_TABLE
#define L2_DESTINATION_TBL_MAX					L2_DESTINATION_TABLE_MAX
#define L2_DESTINATION_TBL_ADDR_PER_ENTRY			L2_DESTINATION_TABLE_ADDR_PER_ENTRY

#define L2_AGING_TBL						L2_AGING_TABLE
#define L2_AGING_STATUS_SHADOW_TBL				L2_AGING_STATUS_SHADOW_TABLE

#define L2_DA_HASH_LOOKUP_TBL					L2_DA_HASH_LOOKUP_TABLE
#define L2_HASH_LOOKUP_TBL_MAX					L2_DA_HASH_LOOKUP_TABLE_MAX
#define L2_HASH_LOOKUP_TBL_ADDR_PER_ENTRY			L2_DA_HASH_LOOKUP_TABLE_ADDR_PER_ENTRY

#define L2_AGING_COLLISION_TBL					L2_AGING_COLLISION_TABLE
#define L2_AGING_COLLISION_SHADOW_TBL				L2_AGING_COLLISION_SHADOW_TABLE

#define L2_LOOKUP_COLLISION_TBL					L2_LOOKUP_COLLISION_TABLE
#define L2_LOOKUP_COLLISION_TBL_MAX				L2_LOOKUP_COLLISION_TABLE_MASKS_MAX
#define L2_LOOKUP_COLLISION_TBL_ADDR_PER_ENTRY			L2_LOOKUP_COLLISION_TABLE_MASKS_ADDR_PER_ENTRY

#define L2_LOOKUP_COLLISION_TBL_MASKS				L2_LOOKUP_COLLISION_TABLE_MASKS
#define L2_LOOKUP_COLLISION_TBL_MASKS_MAX			L2_LOOKUP_COLLISION_TABLE_MASKS_MAX
#define L2_LOOKUP_COLLISION_TBL_MASKS_ADDR_PER_ENTRY		L2_LOOKUP_COLLISION_TABLE_MASKS_ADDR_PER_ENTRY

#define L2_HAIRPIN_ENABLE					HAIRPIN_ENABLE

#define RESERVED_MAC_ADDRESS_RANGE_MAX				RESERVED_SOURCE_MAC_ADDRESS_RANGE_MAX
#define RESERVED_MAC_ADDRESS_RANGE_ADDR_PER_ENTRY		RESERVED_SOURCE_MAC_ADDRESS_RANGE_ADDR_PER_ENTRY

/* L3 Table/Register */
#define ROUTER_PORT_MACADDR_TABLE                           ROUTER_PORT_MAC_ADDRESS
#define ROUTER_PORT_MACADDR_TABLE_MAX                       ROUTER_PORT_MAC_ADDRESS_MAX
#define ROUTER_PORT_MACADDR_TABLE_ADDR_PER_ENTRY            ROUTER_PORT_MAC_ADDRESS_ADDR_PER_ENTRY

#define L3_ROUTING_DEFAULT_TBL                            L3_ROUTING_DEFAULT
#define L3_ROUTING_DEFAULT_TBL_MAX                        L3_ROUTING_DEFAULT_MAX

#define INGRESS_ROUTER_TBL                                INGRESS_ROUTER_TABLE
#define INGRESS_ROUTER_TBL_MAX                            INGRESS_ROUTER_TABLE_MAX

#define NEXT_HOP_TBL                                      NEXT_HOP_TABLE
#define NEXT_HOP_TBL_MAX                                  NEXT_HOP_TABLE_MAX
#define NEXT_HOP_TBL_ADDR_PER_ENTRY                       NEXT_HOP_TABLE_ADDR_PER_ENTRY

#define INGR_EGR_PORT_PKT_TYPE_FILTER_TBL                 INGRESS_EGRESS_PORT_PACKET_TYPE_FILTER
#define INGR_EGR_PORT_PKT_TYPE_FILTER_TBL_MAX             INGRESS_EGRESS_PORT_PACKET_TYPE_FILTER_MAX

#define NEXT_HOP_PACKET_MODIFY_TBL                        NEXT_HOP_PACKET_MODIFICATIONS
#define NEXT_HOP_PACKET_MODIFY_TBL_MAX                    NEXT_HOP_PACKET_MODIFICATIONS_MAX
#define NEXT_HOP_PACKET_MODIFY_TBL_ADDR_PER_ENTRY         NEXT_HOP_PACKET_MODIFICATIONS_ADDR_PER_ENTRY

#define NEXT_HOP_DA_MAC_TBL                               NEXT_HOP_DA_MAC
#define NEXT_HOP_DA_MAC_TBL_MAX                           NEXT_HOP_DA_MAC_MAX
#define NEXT_HOP_DA_MAC_TBL_ADDR_PER_ENTRY                NEXT_HOP_DA_MAC_ADDR_PER_ENTRY

#define HASH_BASED_L3_ROUTING_TBL                         HASH_BASED_L3_ROUTING_TABLE
#define HASH_BASED_L3_ROUTING_TBL_MAX                     HASH_BASED_L3_ROUTING_TABLE_MAX
#define HASH_BASED_L3_ROUTING_TBL_ADDR_PER_ENTRY          HASH_BASED_L3_ROUTING_TABLE_ADDR_PER_ENTRY

/* VLAN */
#define INGRESS_VID_VID_RANGE_SEARCH_DATA_MAX			INGRESS_VID_INNER_VID_RANGE_SEARCH_DATA_MAX

#endif /* _DUBHE1000_SWITCH_REGS_H_ */

