######################################
##-- mcproxy configuration script --##
######################################

# Protocol: IGMPv1|IGMPv2|IGMPv3 (IPv4) - MLDv1|MLDv2 (IPv6)
protocol MLDv1;

pinstance myProxy: "eth0" ==> "br-lan";
