#!/bin/sh /etc/rc.common
# Copyright (c) 2021-2024, Clourney Semiconductor. All rights reserved.
#
# This software and/or documentation is licensed by Clourney Semiconductor under limited terms and conditions.
# Reproduction and redistribution in binary or source form, with or without modification,
# for use solely in conjunction with a Clourney Semiconductor chipset, is permitted in condition which
# must retain the above copyright notice.
#
# By using this software and/or documentation, you agree to the limited terms and conditions.

START=99
USE_PROCD=1

start_service() {
	wfa_mode=`fw_printenv wfa_mode -n 2>/dev/NULL`
	br_lan_ip=`uci get network.lan.ipaddr`

	if [ "$wfa_mode" == "" ];then
		echo "wfa_mode is disabled."
		return
	fi

	echo "cls_dut -i br-lan -p 8000 -l 7"
	procd_open_instance cls_dut
	procd_set_param command /usr/sbin/cls_dut -i br-lan -p 8000 -l 7
	procd_close_instance

	echo "sleep 1; cls_ca -i br-lan -p 9000 -I $br_lan_ip -P 8000"
	procd_open_instance cls_ca
	procd_set_param command /bin/sh -c "sleep 1; /usr/sbin/cls_ca -i br-lan -p 9000 -I $br_lan_ip -P 8000"
	procd_close_instance

	/etc/init.d/cls-mesh stop
}

stop_service() {
	echo "stop cls-wfa!"
}

service_triggers() {
	procd_add_reload_trigger network
}

reload_service() {
	echo "reload cls-wfa!"
	stop
	start
}
