;#######################################################################
; SPDX-FileCopyrightText: 2021-2022 Unisoc (Shanghai) Technologies Co., Ltd
; SPDX-License-Identifier: LicenseRef-Unisoc-General-1.0
; 
; Copyright 2021-2022 Unisoc (Shanghai) Technologies Co., Ltd
; Licensed under the Unisoc General Software License, version 1.0 (the License);
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
; https://www.unisoc.com/en_us/license/UNISOC_GENERAL_LICENSE_V1.0-EN_US
; Software distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OF ANY KIND, either express or implied.
; See the Unisoc General Software License, version 1.0 for more details.
;#######################################################################

[Log]
; Text log level
; 0, No text log
; 1, Log errors,default value
; 2, Log warnings
; 3, Log runtime information
; 4, Log data only
; 5, Log everything
; 6, Log everything and split log to small files
Level = 0

[Setting]
;single *.logel file threashold (MB)
log_file_threashold=500
;log directory threashold (log_file_threashold*log_dir_threashold MB)
log_dir_threashold=3

[DIAG]
BaudRate=115200
DevPath=/dev/ttyUSB2
;DevPath=/dev/ttyUSB_sprd_diag
;NetIP=1.0.29.73.27
;NetPort=10056

[SMP]
BaudRate=115200
DevPath=/dev/ttyUSB3
;DevPath=/dev/ttyUSB_sprd_log
;DevPath_Dump_Mode=/dev/ttyUSB0
;NetIP=10.29.73.27
;NetPort=10057
;NetIP_Dump_Mode=10.29.73.27

[ASSERT]
AutoDump=1
