#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.slk >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.slk=/luci-static/slk
		set luci.main.mediaurlbase=/luci-static/slk
		commit luci
	EOF
fi

exit 0
