#!/bin/sh /etc/rc.common
#
# Copyright 2019 Xingwang Liao <kuoruan@gmail.com>
# Licensed to the public under the MIT License.
#
USE_PROCD=1
config="bwlist"

append_mode(){
	uci delete $config.mode
	uci set $config.mode=rule
	uci set $config.mode.enabled="$enabled"
	uci set $config.mode.dest='wan'
	uci set $config.mode.src='lan'
	uci set $config.mode.proto='all'
	if [ "$mode" == "white" ];then
		uci set $config.mode.target='REJECT'
		uci set $config.mode.name='REJECT-OTHER'
	elif [ "$mode" == "black" ];then
		uci set $config.mode.target='ACCEPT'
		uci set $config.mode.name='ACCEPT-OTHER'
	fi
	uci commit bwlist
}

validate_bwlist_main() {
	uci_validate_section "$config" "bwlist" "$1" \
		'enabled:bool:0' \
		'mode:string'
}

start_instance() {
	`iptables --flush` #清空防火墙规则
	`/etc/init.d/firewall restart`
	if [ -s /etc/config/firewallon ];then
		cat /etc/config/firewallon > /etc/config/firewall 		#恢复出厂防火墙配置
	else
		cp /etc/config/firewall /etc/config/firewallon
	fi
	cat /etc/config/redirect >> /etc/config/firewall 		#端口转发
	if validate_bwlist_main "$1" ;then						#黑白名单
		if [ "x$enabled" == "x1" ];then
			append_mode
			cat /etc/config/bwlist >> /etc/config/firewall
		else
			uci delete $config.mode
			uci commit bwlist
		fi
	fi
	`/etc/init.d/firewall reload`
	`/etc/init.d/nat start`								#11nat
	`/etc/init.d/firewall restart`
}

service_triggers() {
	procd_add_reload_trigger firewallon
	procd_add_reload_trigger bwlist
	procd_add_reload_trigger redirect
}

start_service() {
	config_load "$config"
	config_foreach start_instance "bwlist"
}