[cwmp]
enable=1
#debug_level value: EMERG:1, ALERT:2, CRIT:3, ERROR:4, WARN:5, NOTICE:6, INFO:7, TRACE:8, DEBUG:9
debug_level=4
#log file size value without unit: unit is K
file_size=100
soap_env=SOAP-ENV
soap_enc=SOAP-ENC
acs_auth=0
cpe_auth=0
event_filename=/etc/cwmpevent.bin


acs_url=http://10.30.103.75:80/acs
ca_file=/etc/ssl/private/ca.pem
ca_password=123456


cpe_manufacture=Clouneysemi
cpe_oui=D04433
cpe_sn=CS8862A_RDK_V2_0001
cpe_name=CS8862A
cpe_pc=WiFi Access Point
cpe_hwver=V1.0
cpe_version=V1.0
cpe_username=cwmp
cpe_password=cwmp
acs_username=cwmp
acs_password=cwmp


[cwmpd]
httpd_port=5400
http_timeout=5
