
country_code=US

interface=wlan1

driver=nl80211
ssid=open
#channel=157
channel=36
hw_mode=a
#hw_mode=any

# QoS support
wmm_enabled=1

macaddr_acl=0

beacon_int=100

# 是否隐藏SSID
ignore_broadcast_ssid=0

auth_algs=1

wpa=0

wpa_passphrase=123456789

wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
#wpa_group_rekey=86400


# log信息
# 两种输出方法：syslog 和 stdout（仅在不分叉到后台时可用）。
# Module bitfield (ORed bitfield of modules that will be logged; -1 = all
# modules):
# bit 0 (1) = IEEE 802.11
# bit 1 (2) = IEEE 802.1X
# bit 2 (4) = RADIUS
# bit 3 (8) = WPA
# bit 4 (16) = driver interface
# bit 6 (64) = MLME
#
# Levels (minimum value for logged events):
#  0 = verbose debugging
#  1 = debugging
#  2 = informational messages
#  3 = notification
#  4 = warning
#
#logger_syslog=63
#logger_syslog_level=0
#logger_stdout=63
#logger_stdout_level=0

# 独立控制程序接口。如果指定了该参数，hostapd将创建这个目录和一个UNIX域套接字，
# 用于侦听来自外部程序(CLI/GUI等)的状态信息和配置请求。
# 套接字文件将基于接口名称命名，因此如果使用多个接口，
# 则可以同时运行多个hostapd进程/接口。
ctrl_interface=/var/run/hostapd


# Basic rate set configuration
# List of rates (in 100 kbps) that are included in the basic rate set.
# If this item is not included, usually reasonable default set is used.
#basic_rates=10 20
#basic_rates=10 20 55 110
#basic_rates=60 120 240
#basic_rates=60 90 120 180 240 360 480 540 65 130 195 260 390 520 130 260 390 520 780 1040 1170 1300

#---------------------- 11n -------------------------------------
ieee80211n=1
#require_ht=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40]
#ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]
#ht_capab=[LDPC][SMPS-DYNAMIC][TX-STBC][RX-STBC-1][MAX-AMSDU-7935][DSSS_CCK-40]
#ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][LDPC]
#ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][LDPC][DSSS_CCK-40]


#---------------------- 11ac -------------------------------------
ieee80211ac=1
#require_vht=1
ieee80211d=1
ieee80211h=1
#vht_capab=[MAX-MPDU-11454]
#vht_capab=[MAX-MPDU-7991]

vht_capab=[MAX-MPDU-7991][RXLDPC][SU-BEAMFORMER][BF-ANTENNA-2][SOUNDING-DIMENSION-2][VHT-LINK-ADAPT2]

vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42

#use_sta_nsts=1

