
country_code=US

interface=wlan1

driver=nl80211
ssid=d2k
channel=36
hw_mode=a

# QoS support
wmm_enabled=1

macaddr_acl=0

beacon_int=100

#wds_sta=1
#wds_bridge=br0


# 是否隐藏SSID
ignore_broadcast_ssid=0

auth_algs=1

wpa=0

wpa_passphrase=123456789

wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
rsn_pairwise=CCMP
wpa_group_rekey=86400


# log信息
# 两种输出方法：syslog 和 stdout（仅在不分叉到后台时可用）。
# Module bitfield (ORed bitfield of modules that will be logged; -1 = all
# modules):
# bit 0 (1) = IEEE 802.11
# bit 1 (2) = IEEE 802.1X
# bit 2 (4) = RADIUS
# bit 3 (8) = WPA
# bit 4 (16) = driver interface
# bit 6 (64) = MLME
#
# Levels (minimum value for logged events):
#  0 = verbose debugging
#  1 = debugging
#  2 = informational messages
#  3 = notification
#  4 = warning
#
#logger_syslog=63
#logger_syslog_level=0
#logger_stdout=63
#logger_stdout_level=0

# 独立控制程序接口。如果指定了该参数，hostapd将创建这个目录和一个UNIX域套接字，
# 用于侦听来自外部程序(CLI/GUI等)的状态信息和配置请求。
# 套接字文件将基于接口名称命名，因此如果使用多个接口，
# 则可以同时运行多个hostapd进程/接口。
ctrl_interface=/var/run/hostapd


# Basic rate set configuration
# List of rates (in 100 kbps) that are included in the basic rate set.
# If this item is not included, usually reasonable default set is used.
#basic_rates=10 20
#basic_rates=10 20 55 110
#basic_rates=60 120 240
#basic_rates=60 90 120 180 240 360 480 540 65 130 195 260 390 520 130 260 390 520 780 1040 1170 1300

#---------------------- 11n -------------------------------------
ieee80211n=1
require_ht=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40][MAX-AMSDU-7935]
#ht_capab=[LDPC][SMPS-DYNAMIC][TX-STBC][RX-STBC-1][MAX-AMSDU-7935][DSSS_CCK-40]

#---------------------- 11ac -------------------------------------
ieee80211ac=1
require_vht=1
ieee80211d=1
ieee80211h=1
vht_capab=[MAX-A-MPDU-LEN-EXP7][MAX-MPDU-7991][RXLDPC][SHORT-GI-80][SHORT-GI-160][RX-STBC-1]
#vht_capab=[SOUNDING-DIMENSION-2][BF-ANTENNA-2]
vht_oper_chwidth=1
#vht_oper_centr_freq_seg0_idx=42


#---------------------- 11ax -------------------------------------
ieee80211ax=1

# disable_11ax: Boolean (0/1) to disable HE for a specific BSS
#disable_11ax=0

#he_su_beamformer: HE single user beamformer support
# 0 = not supported (default)
# 1 = supported
he_su_beamformer=1

#he_su_beamformee: HE single user beamformee support
# 0 = not supported (default)
# 1 = supported
#he_su_beamformee=1

#he_mu_beamformer: HE multiple user beamformer support
# 0 = not supported (default)
# 1 = supported
he_mu_beamformer=1

# he_bss_color: BSS color (1-63)
he_bss_color=1

#he_default_pe_duration: The duration of PE field in an HE PPDU in us
# Possible values are 0 us (default), 4 us, 8 us, 12 us, and 16 us
#he_default_pe_duration=0


#he_basic_mcs_nss_set: Basic NSS/MCS set
# 16-bit combination of 2-bit values of Max HE-MCS For 1..8 SS; each 2-bit
# value having following meaning:
# 0 = HE-MCS 0-7, 1 = HE-MCS 0-9, 2 = HE-MCS 0-11, 3 = not supported
#he_basic_mcs_nss_set
#he_basic_mcs_nss_set=2

he_oper_chwidth=1
he_oper_centr_freq_seg0_idx=42

#Clourneysemi
vendor_elements=dd03D04433

ap_max_inactivity=3000
