# wpa_supplicant minimal config

update_config=1

ctrl_interface=/var/run/wpa_supplicant_wlan0
ctrl_interface_group=0

# IEEE 802.1X/EAPOL version
# wpa_supplicant is implemented based on IEEE Std 802.1X-2004 which defines
# EAPOL version 2. However, there are many APs that do not handle the new
# version number correctly (they seem to drop the frames completely). In order
# to make wpa_supplicant interoperate with these APs, the version number is set
# to 1 by default. This configuration value can be used to set it to the new
# version (2).
# Note: When using MACsec, eapol_version shall be set to 3, which is
# defined in IEEE Std 802.1X-2010.
eapol_version=1

#country=CN
country=US

## PMKSA最大的存活时间（秒）;默认为43200
#dot11RSNAConfigPMKLifetime=43200
## 重认证的阈值（PMK存活时间的百分比）；默认为70
#dot11RSNAConfigPMKReauthThreshold=70
## 安全关联协议的超时时间（秒）；默认为60
#dot11RSNAConfigSATimeout=60


#wps_priority=0
#bss_max_count=200

#filter_ssids=0

## 默认的MAC 地址规则
## 0：使用永久的MAC地址
## 1：给每个连接的ESS使用随机的MAC地址
## 2：类似于1，但是保持 OUI（本地管理位集）
#mac_addr=0

## 随机MAC地址的存活时间（秒）（默认为60s）
#rand_addr_lifetime=60

#auto_interworking=0

## 禁用P2P功能
p2p_disabled=1











